Implement SQLite Store using gorm and relational approach
netbirdio/netbird pull request #1065
Opened 2023-08-08 18:50 UTC by surik

## Describe your changes

This approach involves loading associated tables into slices and then converting them into maps. This technique is introducing additional fields prefixed with 'G' (shows Gorm relation), allowing for granular resource management without many changes to existing structures. While this approach introduces complexities, it serves the goal of achieving a functional implementation while minimizing disruptions to the current architecture.

One significant advantage is the elimination of the complexity associated with the lookup table used in the document-oriented approach. This simplification not only enhances query performance but also contributes to improved write speed, especially as the number of accounts grows.

Another key advantage introduced by the new relational approach is the ability to operate on separated data structures, such as accounts, users, and peers, independently. This level of separation empowers more granular and focused updates, ensuring that modifications to one resource do not require loading the entire account. But this may require additional changes in the Store interface and the Account Manager.

#### Benchmark Results:

```
```

We can see that the write speed of the relational approach is better compared with the result shown in #1030. 
Unfortunately, the reading speed is worse but this might be due to the amount of copying I have to do when loading an account. This can be improved.

#### ERD diagram:

**Important to know**: The main identifier for the accounts table is purposely set as aid. This is done to prevent conflicts with the IDs of nested structures. It's possible that this could be due to a problem in Gorm or a misunderstanding on my part about how embedding functions in that context.

<img width="1142" alt="image" src="https://github.com/netbirdio/netbird/assets/708165/53f25954-397d-40ae-84e2-8895d604b69e">

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-08-24 13:48 UTC, surik commented
I managed to make all tests pass with SQLite implementation. Additionally, the testing matrix is extended to cover both file and SQLite store scenarios. The only exception is Windows as I keep getting:

```
testing.go:1206: TempDir RemoveAll cleanup: remove C:\Windows\TEMP\TestSqlite_GetTokenIDByHashedToken2617861885\001\store.db: The process cannot access the file because it is being used by another process.
```

This needs further investigation about the cleanup procedure. For now, testing for Windows only happens with the file store.

2023-08-24 13:55 UTC, surik commented
I managed to make all tests pass with SQLite implementation. The testing matrix is extended to cover both file and SQLite store scenarios. The only exception is Windows as I keep getting:

```
testing.go:1206: TempDir RemoveAll cleanup: remove C:\Windows\TEMP\TestSqlite_GetTokenIDByHashedToken2617861885\001\store.db: The process cannot access the file because it is being used by another process.
```

This seems related to the cleanup procedure and needs further investigation. For now, SQLite store tests are disabled for Windows.

I also added a sub-command that can help with the migration of json storage to the SQLite store:

```
./management migration --help
Migrate JSON file store to SQLite store. Please make a backup of the store json file before running this command.

This command reads the content of {datadir}/store.json and migrates it to {datadir}/store.db that can be used by SQLite store driver.

Usage:
  netbird-mgmt migration [--datadir directory] [--log-file console] [flags]
```

By default, management uses JSON file store as before. To use SQLite there is an option in the config file `StoreKind` which can be set either to `Sqlite` or `JsonFile`.

2023-09-12 15:39 UTC, surik commented
I managed to fix Sqlite store tests on Windows by not using `cache=shared`. Also, made a few manual tests locally and could not find any issues. Saying that this one is ready for review.

2023-09-14 12:53 UTC, pappz requested changes

2023-09-14 12:53 UTC, pappz commented on management/server/sqlite_store.go
> +// NewSqliteStoreFromFileStor restores a store from FileStore and stores SQLite DB in the file located in datadir
Typo mistake in the "NewSqliteStoreFromFileStor".

2023-09-14 16:18 UTC, pappz requested changes

2023-09-14 16:18 UTC, pappz commented on management/server/sqlite_store.go
> +func NewSqliteStoreFromFileStore(filestore *FileStore, dataDir string, metrics telemetry.AppMetrics) (*SqliteStore, error) {
Looks like that the migration of the "installation id" is missing.

2023-09-25 07:10 UTC, pappz requested changes
Because the global lock doing nothing then [this](https://github.com/netbirdio/netbird/pull/1065/files#diff-998d2ca8f48ecbf2d1a259f3851048dacc8f8ae1dfc13c0e69a34e74eaae817aR734) line may cause problem. Here we write out the account but without account lock.

2023-09-28 12:09 UTC, surik commented
The global lock was implemented for SQLite. I managed to eliminate the usage of one global lock-in [here](https://github.com/netbirdio/netbird/pull/1178). We may consider addressing the rest later.

Additionally, I implemented a rollback command in case someone wants to migrate back from SQLite to the JSON store.

Also, I made a few correctness checks by migrating a test `store.json` to `store.db` and then back to `store.json`. This may look like the following:
```
# you need store.json in CWD
$ go build -o mgmt ./management
$ ./mgmt sqlite-migration up --log-file console --datadir .
$ mv store.json store.before.json
$ ./mgmt sqlite-migration down --log-file console --datadir .
```

Then you have both `store.before.json` and `store.json`. Just run diff on them or use any other tool to compare two JSONs. There may be some differences mostly related to the way how JSON is serialized. You may see things like this:

```
12c12
<                     "AccountID": "",
---
>                     "AccountID": "b000jehgmce4vh1360cc",
...
312c312
<                     "Peers": null
---
>                     "Peers": []
...
3332,3334c3334,3338
<             "Routes": null,
<             "NameServerGroups": null,
<             "DNSSettings": null,
---
>             "Routes": {},
>             "NameServerGroups": {},
>             "DNSSettings": {
>                 "DisabledManagementGroups": null
>             },
```

Which mostly are equivalents in the current file store implementation.

Management should behave the same way with `store.json` after `up` and `down` migration.

2023-10-09 09:52 UTC, pappz commented on management/server/sqlite_store.go
> +		//all = append(all, account.Copy()) // TODO: copy and delete gorm models
Is this comment still valid?

2023-10-09 10:31 UTC, surik commented on management/server/sqlite_store.go
> +		//all = append(all, account.Copy()) // TODO: copy and delete gorm models
Good caught. Removed.

2023-10-09 22:16 UTC, pappz submitted a review, later dismissed

2023-10-12 10:04 UTC, mlsmaycon approved these changes

2023-10-12 13:42 UTC, merged