Update GitHub Actions and Enhance golangci-lint
netbirdio/netbird pull request #1075
Opened 2023-08-11 09:33 UTC by surik

## Describe your changes

This PR showcases the implementation of additional linter rules. I've updated the `golangci-lint` GitHub Actions to the latest available version. This update makes sure that the tool works the same way locally - assuming being updated regularly - and with the GitHub Actions.

I've also taken care of keeping all the GitHub Actions up to date, which helps our code stay current. But there's one part, `goreleaser` that's a bit tricky to test on our computers. So, it's important to take a close look at that.

To make it easier to understand what I've done, I've made separate changes for each thing that the new linters found. This should help the people reviewing the changes see what's going on more clearly. Some of the changes might not be obvious at first glance.

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-08-24 13:56 UTC, surik commented
Hi @braginini @mlsmaycon what do you think about this one?

2023-09-01 23:23 UTC, bcmmbaga requested changes

2023-09-01 23:23 UTC, bcmmbaga commented on client/internal/routemanager/client.go
> +	// TODO: should error and non Connected statuses be split?
Is there a specific use case or design consideration behind this `TODO` comment?

2023-09-01 23:23 UTC, bcmmbaga commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
minor the response is io.NopCloser, means it's a no-op when the caller does Close() on the body. It won't harm to call Close(), but it won't actually do anything because of the NopClose.

2023-09-01 23:23 UTC, bcmmbaga commented on management/server/route.go
> +	// TODO: This place is not clear. We've already checked the error above but there is additional logic.
It's important to have a clear understanding of what this part is doing before proceeding merging this. @mlsmaycon can you help here?

2023-09-02 20:04 UTC, mlsmaycon commented on management/server/route.go
> +	// TODO: This place is not clear. We've already checked the error above but there is additional logic.
this second err check can be removed, as it is a left over from a refactor, the loop provides the necessary check already.

2023-09-04 11:06 UTC, surik commented on client/internal/routemanager/client.go
> +	// TODO: should error and non Connected statuses be split?
Hi @bcmmbaga, the `nilerr` linter pointed to this so I wanted to get attention as I may not be fully aware of the logic here. The `removeRouteFromWireguardPeer` returns `nil` when  `err` is not nil. Should we split `if err != nil || state.ConnStatus != peer.StatusConnected` to two cases?

2023-09-04 11:27 UTC, bcmmbaga commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
@surik Can you also remove the close call in these lines? [line#272](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R272), [line#300](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R300), [line#337](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R337), [line#397](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R397), [line#425](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R425), [line#479](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R479) and [line#496](https://github.com/netbirdio/netbird/pull/1075/commits/f89804c53f3bab5981a7a598fc15817c77158d66#diff-cc2813e3131a9e44547b4296fb2c8ce749fa988b8010cd8aa9b9c7c7c0276fc8R479)

2023-09-04 11:32 UTC, bcmmbaga commented on client/internal/routemanager/client.go
> +	// TODO: should error and non Connected statuses be split?
@mlsmaycon, could you assist with this please?

2023-09-04 11:35 UTC, surik commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
@bcmmbaga Yes, sure. Do you prefer to completely disable `bodyclose` linter or only make an exception for these lines?

2023-09-04 11:44 UTC, mlsmaycon commented on client/internal/routemanager/client.go
> +	// TODO: should error and non Connected statuses be split?
we can rewrite it to call `c.wgInterface.RemoveAllowedIP(peerKey, c.network.String())` only when the error is nil and the peer is connected

2023-09-04 11:54 UTC, bcmmbaga commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
We should not disable the check. Only remove the body close on authentik.go, as it is a no-op

2023-09-04 11:57 UTC, surik commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
OK, I see. I'm afraid the linter may complain then. Let me try it out.

2023-09-04 12:26 UTC, surik commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
Yes, it complains. See https://github.com/netbirdio/netbird/actions/runs/6073134678/job/16474466067

```
management/server/idp/authentik.go:236:10: response body must be closed (bodyclose)
                Execute()
                       ^
management/server/idp/authentik.go:267:87: response body must be closed (bodyclose)
        user, resp, err := am.apiClient.CoreApi.CoreUsersRetrieve(ctx, int32(userPk)).Execute()
                                                                                             ^
management/server/idp/authentik.go:294:98: response body must be closed (bodyclose)
        userList, resp, err := am.apiClient.CoreApi.CoreUsersList(ctx).Attributes(accountFilter).Execute()
                                                                                                        ^
management/server/idp/authentik.go:330:72: response body must be closed (bodyclose)
        userList, resp, err := am.apiClient.CoreApi.CoreUsersList(ctx).Execute()
                                                                              ^
management/server/idp/authentik.go:389:101: response body must be closed (bodyclose)
        user, resp, err := am.apiClient.CoreApi.CoreUsersCreate(ctx).UserRequest(createUserRequest).Execute()
```

I believe `bodycheck` just wants consistency for all. I'm not familiar with `goauthentik` package. Does no-op close obvious here without reading the code of the `Execute` method? If not and if this doesn't hurt to call it maybe it makes sense to keep closing them. Let me know what you think.

2023-09-04 12:36 UTC, bcmmbaga commented on management/server/idp/authentik.go
> +	defer resp.Body.Close()
Okay, let's include them

2023-09-04 12:38 UTC, surik commented on client/internal/routemanager/client.go
> +	// TODO: should error and non Connected statuses be split?
I've addressed it in https://github.com/netbirdio/netbird/pull/1075/commits/e4bf3bcadf3dcacdb6ff70b78588cc6b9096b751

2023-09-04 14:59 UTC, bcmmbaga approved these changes

2023-09-04 15:03 UTC, merged