fix NETBIRD_SIGNAL_PORT not working with custom port (#1143)
netbirdio/netbird pull request #1145
Opened 2023-09-13 13:56 UTC by Fantu

Use NETBIRD_SIGNAL_PORT variable instead of the static port for signal container in the docker-compose template to make setting of custom signal port working

## Describe your changes
trying to use custom signal port I saw it was not working and signal container still use the default one.
after a fast look to commit that implement it and comparing with other variable for custom port working I found the missing in docker template that still have the static port to default.
This patch add the use of variable instead of the static port.
From a test seems now working correctly with custom port.

## Issue ticket number and link

### Checklist
- [X] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-09-13 13:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=1145) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=1145) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=1145) it.</sub>

2023-09-14 13:03 UTC, mlsmaycon requested changes
Hello @Fantu Thanks for the contribution. 

To avoid further cases where we miss this configuration, can you please add a test for this port update?

You can add a unique value in the https://github.com/netbirdio/netbird/blob/main/infrastructure_files/tests/setup.env

And then do a grep check similar to the ones in the workflow file: https://github.com/netbirdio/netbird/blob/main/.github/workflows/test-infrastructure-files.yml#L85

2023-09-14 13:47 UTC, Fantu commented
@mlsmaycon thanks for reply
I don't have enough experience on these parts, I had never used netbird (only fast test on debug issue related to signal) and like other things my employer told me to prepare the netbird server for his use and/or that of others and then later told me to fix it given the functioning problem of the signal part and seeing which was urgent for him I looked into it and found/fixed the problem (was easy and fast without study the parts in this case) and after testing that it worked I made the pull request to help the project

I didn't see other custom ports in tests/setup.env so I'm not able to guess how to do the correct implementation without know how it works

2023-09-14 13:57 UTC, mlsmaycon approved these changes
@Fantu no worries, thanks again for the contribution. 

We will add the tests in a new PR.

2023-09-14 13:58 UTC, merged