Fix IPv6 format for DNS address received from android
netbirdio/netbird pull request #1350
Opened 2023-12-01 12:35 UTC by mlsmaycon

## Describe your changes

this adds the address in the expected format in Go [ipv6]:port

## Issue ticket number and link

### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-12-01 12:40 UTC, surik commented on client/internal/dns/server.go
> +	log.Debugf("formated ns: %s", n)
codespell complain here

2023-12-01 12:53 UTC, pappz requested changes

2023-12-01 12:53 UTC, pappz commented on client/internal/dns/server.go
> +	log.Debugf("formated ns: %s", n)
I think these two debug log is too much. We will print out "formatted ns:..." in case of ipv6 only.

2023-12-01 12:53 UTC, pappz commented on client/internal/dns/server.go
> +			ipString = fmt.Sprintf("[%s]", ua)
the port number is not required here?

2023-12-01 12:57 UTC, mlsmaycon commented on client/internal/dns/server.go
> +			ipString = fmt.Sprintf("[%s]", ua)
it is added below

2023-12-01 13:06 UTC, surik approved these changes

2023-12-01 13:24 UTC, pappz approved these changes

2023-12-01 13:26 UTC, merged

2024-07-16 20:46 UTC, WolfgangDpunkt commented
> this adds the address in the expected format in Go [ipv6]:port

I think this would also have to be adapted for the Linux client.
Every ipv6 DNS address that I enter via the Management Gui results in this error message on a debian server client:

`dial udp: address 2001:4860:4860::8888:53: too many colons in address`