quickstart script support custom ports and ssl certificates
netbirdio/netbird pull request #1410
Opened 2023-12-26 10:03 UTC by jiangslee

## Describe your changes
Ports 80, 8080, and 443 of our self-host server have been occupied, and deployment cannot be completed through the quickstart script. 

This modification enables the script to support custom ports and SSL certificates, which solves the issue of #1408 #1267, but it feels not elegant enough. 

Hope other developers can participate and continue to improve it.

I'm very sorry, my English is poor, so I used Google Translate.

## Issue ticket number and link
#1408 
#1267 

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-12-26 10:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=1410) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=1410) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=1410) it.</sub>

2023-12-27 20:25 UTC, mlsmaycon commented
Hello @jiangslee, thank you so much for the contribution; we really appreciate the work you are doing for the community. 

Regarding the required custom port input, we should keep them optional for now; perhaps we can use a flag like `NETBIRD_INTERATIVE_MODE=true` to make the script ask for domain and ports.

This is causing the issue with github workflow:
```shell
2023-12-27T19:23:11.1641432Z ++ echo -n 'Enter the http port you want to use for NetBird (e.g. 80): '
2023-12-27T19:23:11.1642880Z Enter the http port you want to use for NetBird (e.g. 80): ++ read -r READ_NETBIRD_HTTP_PORT
2023-12-27T19:23:11.1644452Z infrastructure_files/getting-started-with-zitadel.sh: line 437: /dev/tty: No such device or address
2023-12-27T19:23:11.1645629Z ++ check_nb_http_port ''
2023-12-27T19:23:11.1646239Z ++ HTTP_PORT=
2023-12-27T19:23:11.1646735Z ++ '[' -x == -x ']'
2023-12-27T19:23:11.1647448Z ++ echo 'The NETBIRD_HTTP_PORT variable cannot be empty.'
2023-12-27T19:23:11.1648369Z The NETBIRD_HTTP_PORT variable cannot be empty.
2023-12-27T19:23:11.1649359Z ++ return 1
2023-12-27T19:23:11.1649833Z ++ read_nb_http_port
2023-12-27T19:23:11.1650447Z ++ READ_NETBIRD_HTTP_PORT=
2023-12-27T19:23:11.1651328Z ++ echo -n 'Enter the http port you want to use for NetBird (e.g. 80): '
2023-12-27T19:23:11.1653023Z Enter the http port you want to use for NetBird (e.g. 80): ++ read -r READ_NETBIRD_HTTP_PORT
2023-12-27T19:23:11.1654770Z infrastructure_files/getting-started-with-zitadel.sh: line 437: /dev/tty: No such device or address
2023-12-27T19:23:11.1655867Z ++ check_nb_http_port ''
2023-12-27T19:23:11.1656403Z ++ HTTP_PORT=
2023-12-27T19:23:11.1657027Z ++ '[' -x == -x ']'
2023-12-27T19:23:11.1657701Z ++ echo 'The NETBIRD_HTTP_PORT variable cannot be empty.'
2023-12-27T19:23:11.1658644Z The NETBIRD_HTTP_PORT variable cannot be empty.
2023-12-27T19:23:11.1659361Z ++ return 1
```

2024-01-05 09:08 UTC, pappz requested changes

2024-01-05 09:08 UTC, pappz commented on infrastructure_files/getting-started-with-zitadel.sh
> +  #NETBIRD_PORT=80
Please remove the unused lines

2024-01-05 09:08 UTC, pappz commented on infrastructure_files/getting-started-with-zitadel.sh
> +    if ! check_nb_port "$NETBIRD_PORT"; then
It doesn't make sense to check this because the NETBIRD_PORT is empty at this point.

2024-01-05 09:08 UTC, pappz commented on infrastructure_files/getting-started-with-zitadel.sh
> +  #TURN_LISTENING_PORT=3478
Please remove the unused lines

2024-01-05 09:08 UTC, pappz commented on infrastructure_files/getting-started-with-zitadel.sh
> +    #NETBIRD_PORT=443
Please remove the unused lines

2024-01-05 09:08 UTC, pappz commented on infrastructure_files/getting-started-with-zitadel.sh
> +    CADDY_SECURE_DOMAIN=", $NETBIRD_DOMAIN:443"
Is the hardcoded 443 port correct? Maybe the proper port is the NETBIRD_PORT variable.

2024-01-06 02:59 UTC, jiangslee commented on infrastructure_files/getting-started-with-zitadel.sh
> +    CADDY_SECURE_DOMAIN=", $NETBIRD_DOMAIN:443"
> Is the hardcoded 443 port correct? Maybe the proper port is the NETBIRD_PORT variable.

I'm very sorry, I don't have free time to optimize this script recently.
I checked the Caddyfile, and the 443 port here is the port number inside the caddy container. I tried using variables instead, but it didn't work, so I just hardcoded it here.

2024-01-06 03:05 UTC, jiangslee commented on infrastructure_files/getting-started-with-zitadel.sh
> +    CADDY_SECURE_DOMAIN=", $NETBIRD_DOMAIN:443"
```
# CaddyFile:628
# :80, netbird-demo.domain.com:8443 {

root@iZj6c5ea0uadvb1tljqmjoZ:~/docker-netbird# curl -i https://netbird-demo.domain.com:8443
HTTP/2 200 
alt-svc: h3=":443"; ma=2592000
server: Caddy
content-length: 0
date: Sat, 06 Jan 2024 02:58:53 GMT
```
```
root@iZj6c5ea0uadvb1tljqmjoZ:~/docker-netbird# nano Caddyfile 
# CaddyFile:628 CHANGED PORT TO 443
# :80, netbird-demo.domain.com:443 {

```
```
root@iZj6c5ea0uadvb1tljqmjoZ:~/docker-netbird# docker compose restart caddy
[+] Restarting 1/1
 ✔ Container docker-netbird-caddy-1  Started                                                                                                                      0.6s 
root@iZj6c5ea0uadvb1tljqmjoZ:~/docker-netbird# curl -i https://netbird-demo.domain.com:8443
HTTP/2 200 
alt-svc: h3=":443"; ma=2592000
content-type: text/html
date: Sat, 06 Jan 2024 02:59:18 GMT
etag: W/"6596f04e-25a"
last-modified: Thu, 04 Jan 2024 17:52:14 GMT
referrer-policy: strict-origin-when-cross-origin
strict-transport-security: max-age=3600; includeSubDomains; preload
vary: Accept-Encoding
x-content-type-options: nosniff
x-frame-options: DENY
x-xss-protection: 1; mode=block

<!doctype html><html lang="en"><head><meta charset="utf-8"/><link rel="icon" href="/favicon.ico"/><meta name="viewport" content="width=device-width,initial-scale=1"/><meta name="theme-color" content="#000000"/><meta name="robots" content="noindex"><meta name="description" content="NetBird Management Dashboard"/><link rel="manifest" href="/manifest.json"/><title>NetBird</title><script defer="defer" src="/static/js/main.436624eb.js"></script><link href="/static/css/main.940e3c70.css" rel="stylesheet"></head><body><noscript>NetBird Management Dashboard.</noscript><div id="root"></div></body></html>

```

2024-01-08 11:39 UTC, mlsmaycon requested changes
Thanks @jiangslee for the changes and the time you are investing on this. 

I've make some suggestions and requests. The main point is that these changes should be optional and only requested if the user wants to by setting the NETBIRD_INTERACTIVE_MODE. 

Regarding port 8080, it was a left over from the initial setup and can be removed.

2024-01-08 11:39 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +    fi
```suggestion
    if [[ "x-$NETBIRD_INTERATIVE_MODE" == "x-true" ]]; then 
        if ! check_nb_http_port "$NETBIRD_HTTP_PORT"; then
          NETBIRD_HTTP_PORT=$(read_nb_http_port)
        fi
    
        if ! check_nb_http_port "$NETBIRD_8080_PORT"; then
          NETBIRD_8080_PORT=$(read_nb_8080_port)
        fi
    
        if ! check_nb_3478_port "$TURN_LISTENING_PORT"; then
          TURN_LISTENING_PORT=$(read_nb_3478_port)
        fi
        if ! check_nb_port "$NETBIRD_PORT"; then
          NETBIRD_PORT=$(read_nb_port)
        fi
    fi  
```

2024-01-08 11:39 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
Let's set default ports to be used when the user is not using the interactive mode.

2024-01-08 11:39 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +$NETBIRD_DOMAIN {
What is the effect of this setting? Does caddy will look for the certificates if none is provided? Does it fail? I think this block should be optional.

2024-01-08 11:39 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +      - '$NETBIRD_8080_PORT:8080'
This can be removed, it is probably a leftover

2024-01-13 10:25 UTC, jiangslee commented on infrastructure_files/getting-started-with-zitadel.sh
> +$NETBIRD_DOMAIN {
Yes, this should be optional. I will see how to change it to optional. Thanks.

2024-01-13 10:26 UTC, jiangslee commented on infrastructure_files/getting-started-with-zitadel.sh
> +      - '$NETBIRD_8080_PORT:8080'
OK, I will remove it.

2024-01-16 14:09 UTC, liuyishengaaa commented
> ```
> ~/docker-netbird# export NETBIRD_DOMAIN=netbird-demo.domain.com
> ~/docker-netbird# bash getting-started-with-zitadel.sh 
> The NETBIRD_HTTP_PORT variable cannot be empty.
> Enter the http port you want to use for NetBird (e.g. 80): 8088
> The NETBIRD_HTTP_PORT variable cannot be empty.
> Enter the NETBIRD_8080_PORT you want to use for NetBird (e.g. 8080): 8081
> The NETBIRD_3478_PORT variable cannot be empty.
> Enter the TURN_LISTENING_PORT you want to use for NetBird (e.g. 3478): 3478
> The NETBIRD_PORT variable cannot be empty.
> Enter the https port you want to use for NetBird (e.g. 443): 8443
> Rendering initial files...
> 
> Initializing Zitadel's CockroachDB
> 
> 
> [+] Running 7/7
>  ✔ Network docker-netbird_netbird                 Created                                                                                                                                  0.1s 
>  ✔ Volume "docker-netbird_netbird_caddy_data"     Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_management"     Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_zitadel_certs"  Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_crdb_data"      Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_crdb_certs"     Created                                                                                                                                  0.0s 
>  ✔ Container docker-netbird-crdb-1                Started                                                                                                                                  0.1s 
> 
> Waiting cockroachDB  to become ready  . done
> 
> Starting Zidatel IDP for user management
> 
> 
> [+] Running 3/3
>  ✔ Container docker-netbird-caddy-1    Started                                                                                                                                             0.2s 
>  ✔ Container docker-netbird-crdb-1     Healthy                                                                                                                                             0.0s 
>  ✔ Container docker-netbird-zitadel-1  Started                                                                                                                                             0.2s 
> 
> Initializing Zitadel with NetBird's applications
> 
> Waiting for Zitadel's PAT to be created  . . . . done
> Reading Zitadel PAT
> Waiting for Zitadel to become ready  . . . . . . . . . . . . . done
> Creating new zitadel project
> Creating new Zitadel SPA Dashboard application
> Creating new Zitadel SPA Cli application
> 
> Rendering NetBird files...
> 
> 
> Starting NetBird services
> 
> [+] Running 7/7
>  ✔ Container docker-netbird-coturn-1      Started                                                                                                                                          0.2s 
>  ✔ Container docker-netbird-crdb-1        Healthy                                                                                                                                          0.0s 
>  ✔ Container docker-netbird-zitadel-1     Running                                                                                                                                          0.0s 
>  ✔ Container docker-netbird-caddy-1       Running                                                                                                                                          0.0s 
>  ✔ Container docker-netbird-dashboard-1   Started                                                                                                                                          0.2s 
>  ✔ Container docker-netbird-signal-1      Started                                                                                                                                          0.2s 
>  ✔ Container docker-netbird-management-1  Started                                                                                                                                          0.2s 
> 
> Done!
> 
> You can access the NetBird dashboard at https://netbird-demo.domain.com:8443
> Login with the following credentials:
> Username: admin@netbird-demo.domain.com
> Password: VBkLImAnyPasswordgdZt6quUsR/kjMH9IrhpO7Tikg@
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/27892476/294655336-06e0a7f3-cc96-473a-96e4-5be650ffe38d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzOTk5NTAsIm5iZiI6MTcwNTM5OTY1MCwicGF0aCI6Ii8yNzg5MjQ3Ni8yOTQ2NTUzMzYtMDZlMGE3ZjMtY2M5Ni00NzNhLTk2ZTQtNWJlNjUwZmZlMzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDEwMDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4ZDUwZWJmYjJiMmJhZTNjZmQ2YmRjZWExMDRhNzRkZGNiMDAxOGVlNzQxNDNhODBlMDEwNTBjYTdlZGIxMTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UrvEh4Syl53TrP-vxGeF85CtAlvybYz90pU3GPjMV3w)


Dear jiangslee：
    您用的哪一个脚本，为啥自定义端口安装后，下图我的没有显示“域名+端口”，只显示了域名呢
![image](https://github.com/netbirdio/netbird/assets/132032777/22caac71-48c6-4c5b-8e2e-ebef1e9946db)


> ```
> ~/docker-netbird# export NETBIRD_DOMAIN=netbird-demo.domain.com
> ~/docker-netbird# bash getting-started-with-zitadel.sh 
> The NETBIRD_HTTP_PORT variable cannot be empty.
> Enter the http port you want to use for NetBird (e.g. 80): 8088
> The NETBIRD_HTTP_PORT variable cannot be empty.
> Enter the NETBIRD_8080_PORT you want to use for NetBird (e.g. 8080): 8081
> The NETBIRD_3478_PORT variable cannot be empty.
> Enter the TURN_LISTENING_PORT you want to use for NetBird (e.g. 3478): 3478
> The NETBIRD_PORT variable cannot be empty.
> Enter the https port you want to use for NetBird (e.g. 443): 8443
> Rendering initial files...
> 
> Initializing Zitadel's CockroachDB
> 
> 
> [+] Running 7/7
>  ✔ Network docker-netbird_netbird                 Created                                                                                                                                  0.1s 
>  ✔ Volume "docker-netbird_netbird_caddy_data"     Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_management"     Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_zitadel_certs"  Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_crdb_data"      Created                                                                                                                                  0.0s 
>  ✔ Volume "docker-netbird_netbird_crdb_certs"     Created                                                                                                                                  0.0s 
>  ✔ Container docker-netbird-crdb-1                Started                                                                                                                                  0.1s 
> 
> Waiting cockroachDB  to become ready  . done
> 
> Starting Zidatel IDP for user management
> 
> 
> [+] Running 3/3
>  ✔ Contain [...]

2024-02-14 03:09 UTC, closed without merging

2024-03-20 07:56 UTC, liuyishengaaa commented
According to the program you provided, the installation can be successful, but only the management container keeps restarting and reporting errors：

“
2024-03-20T07:49:46Z INFO management/cmd/management.go:407: loading OIDC configuration from the provided IDP configuration endpoint https://netbird1.test.buzz:33443/.well-known/openid-configuration
Error: failed reading provided config file: /etc/netbird/management.json: failed fetching OIDC configuration from endpoint https://netbird1.test.buzz:33443/.well-known/openid-configuration Get "https://netbird1.test.buzz:33443/.well-known/openid-configuration": dial tcp [2403:7c51:553:fe82:cc36:12ef:ceca:5bcf]:33443: connect: cannot assign requested address”

![netbird](https://github.com/netbirdio/netbird/assets/132032777/bfecfde9-0825-487b-a86d-b9dc449862ad)

2024-03-20 11:13 UTC, liuyishengaaa commented
Based on the program you just sent, I tested it again and encountered the same issue. Port testing with the "nc" command confirms that the ports are open.

2024-03-20 11:17 UTC, liuyishengaaa commented
If there's a senior developer who can provide the source code for installation instead of deploying it using containers, it would make problem-solving much easier.

2025-02-20 07:34 UTC, 1350962574 commented
> 6. acme.sh（cf dns签发证书，好像可以改caddy直接用cf dns签发证书，不过我还不会）
> 7. 一键docker部署脚本 https://raw.githubusercontent.com/jiangslee/netbird/refs/heads/main-jsl/infrastructure_files/getting-started-with-zitadel.sh

> # 准备工作
> 1. CF配置域名解释，以及在istoreos配置好DDNS-GO
> 2. acme.sh 配置好`CF_TOKEN`、`CF_Account_ID`签发证书
> 3. 跑一键脚本
> 
> 待完善。。。

### caddy直接用cf dns签发证书：
* 新建CF API令牌 将投射的Token拷贝备用
<img width="1649" alt="image" src="https://github.com/user-attachments/assets/71dd102f-28db-45cf-8fa0-2fd751da1464" />

* 修改 Docker-Compose与Caddyfile
> docker-compose.yml
``` version: "3.4"
services:
  # Caddy reverse proxy
  caddy:
    image: iarekylew00t/caddy-cloudflare:latest # 使第三方Caddy镜像
    restart: unless-stopped
    networks: [ netbird ]
    environment:
      - CF_API_TOKEN=<API Token> # Cloudflare Token用于自动签发续期SSL
    ports:
      - '8443:443'
      - '8088:80'
      - '8081:8080'
    volumes:
      - netbird_caddy_data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/certs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # 日志文件最大大小为10MB
        max-file: "3" 
...如下保持不变
```


> Caddyfile
```{
 # DEBUG # 全局调试模式,log等级为Full
  acme_dns cloudflare {env.CF_API_TOKEN} # 引用Docker-Compose文件传入的CF_API_TOKEN变量
  servers :80,:443 {
    protocols h1 h2c
  }
}

storage /certs {

}


(security_headers) {
    header * {
        Strict-Transport-Security "max-age=3600; includeSubDomains; preload"
        X-Content-Type-Options "nosniff"
        X-Frame-Options "DENY"
        X-XSS-Protection "1; mode=block"
        -Server
        Referrer-Policy strict-origin-when-cross-origin
    }
}

domainname.com {
  tls {
    dns cloudflare {env.CF_API_TOKEN} # 引用Docker-Compose文件传入的CF_API_TOKEN变量
  }
  import security_headers
  reverse_proxy /signalexchange.SignalExchange/* h2c://signal:10000
  reverse_proxy /api/* management:80
  reverse_proxy /management.ManagementService/* h2c://management:80
  reverse_proxy /zitadel.admin.v1.AdminService/* h2c://zitadel:8080
  reverse_proxy /admin/v1/* h2c://zitadel:8080
  reverse_proxy /zitadel.auth.v1.AuthService/* h2c://zitadel:8080
  reverse_proxy /auth/v1/* h2c://zitadel:8080
  reverse_proxy /zitadel.management.v1.ManagementService/* h2c://zitadel:8080
  reverse_proxy /management/v1/* h2c://zitadel:8080
  reverse_proxy /zitadel.system.v1.SystemService/* h2c://zitadel:8080
  reverse_proxy /system/v1/* h2c://zitadel:8080
  reverse_proxy /assets/v1/* h2c://zitadel:8080
  reverse_proxy /ui/* h2c://zitadel:8080
  reverse_proxy /oidc/v1/* h2c://zitadel:8080
  reverse_proxy /saml/v2/* h2c://zitadel:8080
  reverse_proxy /oauth/v2/* h2c://zitadel:8080
  reverse_proxy /.well-known/openid-configuration h2c://zitadel:8080
  reverse_proxy /openapi/* h2c://zitadel:8080
  reverse_proxy /debug/* h2c://zitadel:8080
  reverse_proxy /device/* h2c://zitadel:8080
  reverse_proxy /device h2c://zitadel:8080
  reverse_proxy /* dashboard:80
}```

2025-03-13 15:35 UTC, fr58386612 commented
> 5\. error: failed while getting Management Service public key #2043 (comment)

求救：
1.跑一键脚步前是否还要准备好证书到certs目录？
2.跑一键脚步时是否要修改好非80和443端口；
3.端口转发中的9443和8081是转到NPM主机上还是netbird虚拟机上？
4. 你的NPM的https端口是多少？9443吗？这样配置后是不是caddy上面端口就没有用了？
4.改端口的域名不就是NPM反对的域名吗？莫非还不一样？

2025-03-13 15:36 UTC, fr58386612 commented
> > 6. acme.sh（cf dns签发证书，好像可以改caddy直接用cf dns签发证书，不过我还不会）
> > 7. 一键docker部署脚本 https://raw.githubusercontent.com/jiangslee/netbird/refs/heads/main-jsl/infrastructure_files/getting-started-with-zitadel.sh
> 
> > # 准备工作
> > 
> > 1. CF配置域名解释，以及在istoreos配置好DDNS-GO
> > 2. acme.sh 配置好`CF_TOKEN`、`CF_Account_ID`签发证书
> > 3. 跑一键脚本
> > 
> > 待完善。。。
> 
> ### caddy直接用cf dns签发证书：
> * 新建CF API令牌 将投射的Token拷贝备用
> 
> <img alt="image" width="1649" src="https://private-user-images.githubusercontent.com/48989077/415058789-71dd102f-28db-45cf-8fa0-2fd751da1464.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDE4NzgzMDksIm5iZiI6MTc0MTg3ODAwOSwicGF0aCI6Ii80ODk4OTA3Ny80MTUwNTg3ODktNzFkZDEwMmYtMjhkYi00NWNmLThmYTAtMmZkNzUxZGExNDY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzEzVDE1MDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZmM3MzgwMDdmMjdhNDE2Y2FmMzViNWM5ZWVlNjg5OGQ3YWQ1MjYwMzc0MGZmNDYzZmFiZDllNmQ2MGNmNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rTuWB5JsYW87mxU1gdVzisxCuhdWrfYxHfmKzKWZCgY">
> * 修改 Docker-Compose与Caddyfile
> 
> > docker-compose.yml
> 
> ```
> services:
>   # Caddy reverse proxy
>   caddy:
>     image: iarekylew00t/caddy-cloudflare:latest # 使第三方Caddy镜像
>     restart: unless-stopped
>     networks: [ netbird ]
>     environment:
>       - CF_API_TOKEN=<API Token> # Cloudflare Token用于自动签发续期SSL
>     ports:
>       - '8443:443'
>       - '8088:80'
>       - '8081:8080'
>     volumes:
>       - netbird_caddy_data:/data
>       - ./Caddyfile:/etc/caddy/Caddyfile
>       - ./certs:/certs  # 挂载SSL目录
>     logging:
>       driver: "json-file"
>       options:
>         max-size: "10m"    # 日志文件最大大小为10MB
>         max-file: "3" 
> ...如下保持不变
> ```
> 
> > Caddyfile
> 
> ```
>  # DEBUG # 全局调试模式,log等级为Full
>   acme_dns cloudflare {env.CF_API_TOKEN} # 引用Docker-Compose文件传入的CF_API_TOKEN变量
>   servers :80,:443 {
>     protocols h1 h2c
>   }
> }
> 
> storage /certs {
> 
> }
> 
> 
> (security_headers) {
>     header * {
>         Strict-Transport-Security "max-age=3600; includeSubDomains; preload"
>         X-Content-Type-Options "nosniff"
>         X-Frame-Options "DENY"
>         X-XSS-Protection "1; mode=block"
>         -Server
>         Referrer-Policy strict-origin-when-cross-origin
>     }
> }
> 
> domainname.com {
>   tls {
>     dns cloudflare {env.CF_API_TOKEN} # 引用Docker-Compose文件传入的CF_API_TOKEN变量
>   }
>   import security_headers
>   reverse_proxy /signalexchange.SignalExchange/* h2c://signal:10000
>   reverse_proxy /api/* management:80
>   reverse_proxy /management.ManagementService/* h2c://management:80
>   reverse_proxy /zitadel.admin.v1.AdminService/* h2c://zitadel:8080
>   reverse_proxy /admin/v1/* h2c://zitadel:8080
>   reverse_proxy /zitadel.auth.v1.AuthService/* h2c://zitadel:8080
>   reverse_proxy /auth/v1/* h2c://zitadel:8080
>   reverse_proxy /zitadel.management.v1.ManagementService/* h2c://zitadel:8080
>   reverse_proxy /management/v1/* h2c://zitadel:8080
>   reverse_proxy /zitadel.system.v1.SystemService/* h2c://zitadel:8080
>   reverse_proxy /system/v1/* h2c://zitadel:8080
>   reverse_proxy /assets/v1/* h2c://zitadel:8080
>   reverse_proxy /ui/* h2c://zitadel:8080
>   reverse_proxy /oidc/v1/* h2c://zitadel:8080
>   reverse_proxy /saml/v2/* h2c://zitadel:8080
>   reverse_proxy /oauth/v2/* h2c://zitadel:8080
>   reverse_proxy /.well-known/openid-configuration h2c://zitadel:8080
>   reverse_proxy /openapi/* h2c://zitadel:8080
>   reverse_proxy /debug/* h2c://zitadel:8080
>   reverse_proxy /device/* h2c://zitadel:8080
>   reverse_proxy /device h2c://zitadel:8080
>   reverse_proxy /* dashboard:80
> }
> ```

求救：
1.跑一键脚步前是否还要准备好证书到certs目录？
2.跑一键脚步时是否要修改好非80和443端口；
3.端口转发中的9443和8081是转到NPM主机上还是netbird虚拟机上？
4. 你的NPM的https端口是多少？9443吗？这样配置后是不是caddy上面端口就没有用了？
4.改端口的域名不就是NPM反对的域名吗？莫非还不一样？

2025-03-14 03:13 UTC, fr58386612 commented
我事

> > 求救：
> > 1.跑一键脚步前是否还要准备好证书到certs目录？
> > 2.跑一键脚步时是否要修改好非80和443端口；
> > 3.端口转发中的9443和8081是转到NPM主机上还是netbird虚拟机上？
> > 4. 你的NPM的https端口是多少？9443吗？这样配置后是不是caddy上面端口就没有用了？
> > 4.改端口的域名不就是NPM反对的域名吗？莫非还不一样？
> 
> 求救： **1.跑一键脚步前是否还要准备好证书到certs目录？** 跑一键脚本前要先准备好certs目录及域名的证书
> 
> ```
> mkdir certs
> ```
> 
> 在certs目录放好与域名一致的证书文件，如netbird.my-domain.com.pem，netbird.my-domain.com.key
> 
> ```
> ~/docker-netbird# tree certs
> certs
> ├── netbird.my-domain.com.key
> └── netbird.my-domain.com.pem
> 
> ~/docker-netbird# export NETBIRD_DOMAIN=netbird.my-domain.com
> ~/docker-netbird# bash <(curl -sSL https://raw.githubusercontent.com/jiangslee/netbird/refs/heads/main-jsl/infrastructure_files/getting-started-with-zitadel.sh)
> ```
> 
> 按提示输入好端口号（请提前进行域名解释和及安全组端口放行：你自定义的端口号，比如我上图的TCP：8088,8443; UDP ports: 3478, 49152-65535）
> 
> **2.跑一键脚步时是否要修改好非80和443端口；**
> 
> > 不用，按提示输入自定义端口号
> 
> **3.端口转发中的9443和8081是转到NPM主机上还是netbird虚拟机上？**
> 
> > NPM参考这个 [#1410 (comment)](https://github.com/netbirdio/netbird/pull/1410#issuecomment-2603444928)
> 
> **4. 你的NPM的https端口是多少？9443吗？这样配置后是不是caddy上面端口就没有用了？**
> 
> > 我NPM的HTTPS端口是`443`
> 
> 4.改端口的域名不就是NPM反对的域名吗？莫非还不一样？
> 
> > 一样

我使用之前的一键部署脚本，使用ddns解析动态域名到家庭宽带上，路由器做DMZ主机给nas上的虚拟机，在此虚拟机也可以一键部署成功，不知道改成NPM的作用是什么？是为了自动更新ssl证书吗？
目前我更新ssl证书的方案是：
1. 使用lucky的自动更新ssl证书，并把证书映射到/certs目录下；
2. 写一个证书变化自动重启cuddy容器的脚本；
`#!/bin/bash
CERT_PATH="/root/netbird/certs/netbird.xxx.com.key"  # 替换为证书路径
CONTAINER_NAME="netbird-caddy-1"  # 替换为容器名
LAST_UPDATE=$(stat -c %Y "$CERT_PATH")
LAST_RUN=$(cat /tmp/cert_check_last_run 2>/dev/null || echo 0)
echo "证书最后更新时间: $(date -d @$LAST_UPDATE '+%Y-%m-%d %H:%M:%S')"
echo "脚本上次运行时间: $(date -d @$LAST_RUN '+%Y-%m-%d %H:%M:%S')"

if [ "$LAST_UPDATE" -gt "$LAST_RUN" ]; then
  echo "证书已更新，重启Caddy容器..."
  docker restart $CONTAINER_NAME
  echo $(date +%s) > /tmp/cert_check_last_run我事

> > 求救：
> > 1.跑一键脚步前是否还要准备好证书到certs目录？
> > 2.跑一键脚步时是否要修改好非80和443端口；
> > 3.端口转发中的9443和8081是转到NPM主机上还是netbird虚拟机上？
> > 4. 你的NPM的https端口是多少？9443吗？这样配置后是不是caddy上面端口就没有用了？
> > 4.改端口的域名不就是NPM反对的域名吗？莫非还不一样？
> 
> 求救： **1.跑一键脚步前是否还要准备好证书到certs目录？** 跑一键脚本前要先准备好certs目录及域名的证书
> 
> ```
> mkdir certs
> ```
> 
> 在certs目录放好与域名一致的证书文件，如netbird.my-domain.com.pem，netbird.my-domain.com.key
> 
> ```
> ~/docker-netbird# tree certs
> certs
> ├── netbird.my-domain.com.key
> └── netbird.my-domain.com.pem
> 
> ~/docker-netbird# export NETBIRD_DOMAIN=netbird.my-domain.com
> ~/docker-netbird# bash <(curl -sSL https://raw.githubusercontent.com/jiangslee/netbird/refs/heads/main-jsl/infrastructure_files/getting-started-with-zitadel.sh)
> ```
> 
> 按提示输入好端口号（请提前进行域名解释和及安全组端口放行：你自定义的端口号，比如我上图的TCP：8088,8443; UDP ports: 3478, 49152-65535）
> 
> **2.跑一键脚步时是否要修改好非80和443端口；**
> 
> > 不用，按提示输入自定义端口号
> 
> **3.端口转发中的9443和8081是转到NPM主机上还是netbird虚拟机上？**
> 
> > NPM参考这个 [#1410 (comment)](https://github.com/netbirdio/netbird/pull/1410#issuecomment-2603444928)
> 
> **4. 你的NPM的https端口是多少？9443吗？这样配置后是不是caddy上面端口就没有用了？**
> 
> > 我NPM的HTTPS端口是`443`
> 
> 4.改端口的域名不就是NPM反对的域名吗？莫非还不一样？
> 
> > 一样

我使用之前的一键部署脚本，使用ddns解析动态域名到家庭宽带上，路由器做DMZ主机给nas上的虚拟机，在此虚拟机也可以一键部署成功，不知道改成NPM的作用是什么？是为了自动更新ssl证书吗？
目前我更新ssl证书的方案是：
1. 使用lucky的自动更新ssl证书，并把证书映射到/certs目录下；
2. 写一个证书变化自动重启cuddy容器的脚本；
`#!/bin/bash
CERT_PATH="/root/netbird/certs/netbird.xxx.com.key"  # 替换为证书路径
CONTAINER_NAME="netbird-caddy-1"  # 替换为容器名
LAST_UPDATE=$(stat -c %Y "$CERT_PATH")
LAST_RUN=$(cat /tmp/cert_check_last_run 2>/dev/null || echo 0)
echo "证书最后更新时间: $(date -d @$LAST_UPDATE '+%Y-%m-%d %H:%M:%S')"
echo "脚本上次运行时间: $(date -d @$LAST_RUN '+%Y-%m-%d %H:%M:%S')"

if [ "$LAST_UPDATE" -gt "$LAST_RUN" ]; then
  echo "证书已更新，重启Caddy容器..."
  docker restart $CONTAINER_NAME
  echo $(date +%s) > /tmp/cert_check_last_run
else
  echo "证书未更新"
fi`
这样就可以自动更新证书了。
另外请问能否更新下这个自动部署的一键脚本，现在部署出来的是老版本的netbird管理平台，缺失了很多新功能，能更新到最新版吗？
else
  echo "证书未更新"
fi`
这样就可以自动更新证书了。
另外请问能否更新下这个自动部署的一键脚本，现在部署出来的是老版本的netbird管理平台，缺失了很多新功能，能更新到最新版吗？