Add Geo Location posture check
netbirdio/netbird pull request #1500
Opened 2024-01-27 09:41 UTC by bcmmbaga

## Describe your changes

This PR extends the existing `/api/posture-checks` endpoint with  Geo ocation checks.

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-01-31 14:49 UTC, surik requested changes

2024-01-31 14:49 UTC, surik commented on management/server/http/posture_checks_handler.go
> +			if loc.CountryCode == "" {
Maybe we can add basic validation to check the `2-letter ISO 3166-1 alpha-2 code that represents the country`. Later we can validate against location DB.

2024-01-31 14:49 UTC, surik commented on management/server/posture/geo_location.go
> +		if loc.CountryCode == peer.Meta.Location.CountryCode && loc.CityName == peer.Meta.Location.CityName {
We need to consider county-wide checks when CityName is empty

2024-01-31 15:48 UTC, surik commented on management/server/peer/peer.go
>  func (p PeerSystemMeta) isEqual(other PeerSystemMeta) bool {
We probably need to extend this with Location too

2024-01-31 15:55 UTC, bcmmbaga commented on management/server/peer/peer.go
>  func (p PeerSystemMeta) isEqual(other PeerSystemMeta) bool {
I left it intentionally, as we should cover this when we extend the peer metadata with location

2024-01-31 17:13 UTC, surik commented on management/server/http/posture_checks_handler.go
> +			countryCodeRegex := regexp.MustCompile("^[a-zA-Z]{2}$")
We can initialise this as a global variable. No need to compile it each time.

2024-02-01 10:46 UTC, surik approved these changes

2024-02-01 10:54 UTC, merged