Routes is a map, employing safe read/writes ops
netbirdio/netbird pull request #1760
Opened 2024-03-28 00:32 UTC by hurricanehrndz

Adding a mutex to the struct although the norm, could not be used due to the state being copied around.

## Describe your changes

## Issue ticket number and link

### Checklist
- [x ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-03-28 00:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=1760) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=1760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=1760) it.</sub>

2024-03-28 10:23 UTC, lixmal commented on client/internal/routemanager/client.go
> +		//TODO: hurricanehrndz
What's the todo here?

2024-03-28 10:24 UTC, lixmal commented on client/internal/peer/status.go
> +    s.Mux.Lock()
I believe this should be a `RLock()`

2024-03-28 10:29 UTC, lixmal requested changes
Thank you for your contribution @hurricanehrndz. Could you also fix the tests please?

2024-03-28 14:05 UTC, hurricanehrndz commented
> Thank you for your contribution @hurricanehrndz. Could you also fix the tests please?

I can definitely take a look at this weekend

2024-04-04 03:42 UTC, hurricanehrndz commented
@lixmal PR should be good now, squashed all my commits and cleaned up the tests and some formatting issues I had introduce

2024-04-10 11:23 UTC, hurricanehrndz commented
@lixmal is there anything you require of me?

2024-04-11 18:54 UTC, mlsmaycon approved these changes
Approved. 

Thanks @hurricanehrndz

2024-04-11 20:12 UTC, merged