Migrate blob net ip fields to json serializer
netbirdio/netbird pull request #1906
Opened 2024-04-30 07:05 UTC by bcmmbaga

## Describe your changes

Migrates all net ip blob fields to serializer:json.

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-04-30 08:58 UTC, lixmal reviewed
Could you add tests to `migration_test.go` and maybe `sqlite_store_test.go`:`TestMigrate` please

2024-04-30 10:44 UTC, lixmal submitted a review, later dismissed

2024-04-30 12:43 UTC, mlsmaycon reviewed
let's validate using string instead of json for net.IP

2024-04-30 14:17 UTC, mlsmaycon requested changes
let's validate using plain strings for net.IP

2024-05-07 10:03 UTC, lixmal approved these changes

2024-05-07 11:00 UTC, mlsmaycon approved these changes

2024-05-07 11:01 UTC, merged