Generate network maps for routed network
netbirdio/netbird pull request #2068
Opened 2024-05-28 14:24 UTC by bcmmbaga

## Describe your changes

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-05-31 11:13 UTC, lixmal requested changes

2024-05-31 11:13 UTC, lixmal commented on management/proto/management.proto
> +  RuleProtocol protocol = 6;
Do you think we can make this an int? It would require a slightly different implementation but offers more flexibility for the users

2024-05-31 11:13 UTC, lixmal commented on management/server/route.go
> +	// NetworkFamily string
Comment doesn't match

2024-05-31 11:13 UTC, lixmal commented on management/server/route.go
> +				log.Error("failed to parse port %s for rule: %s", port, rule.ID)
```suggestion
				log.Errorf("failed to parse port %s for rule: %s", port, rule.ID)
```

2024-05-31 12:11 UTC, bcmmbaga commented on management/proto/management.proto
> +  RuleProtocol protocol = 6;
Destination or protocol? If the protocol is already of int32 type

2024-05-31 13:04 UTC, lixmal commented on management/proto/management.proto
> +  RuleProtocol protocol = 6;
Protocol is an enum, isn't it?

```
enum RuleProtocol {
  UNKNOWN = 0;
  ALL = 1;
  TCP = 2;
  UDP = 3;
  ICMP = 4;
}
```

2024-05-31 13:35 UTC, bcmmbaga commented on management/proto/management.proto
> +  RuleProtocol protocol = 6;
Yes, it's an enum

2024-06-03 08:07 UTC, lixmal commented on management/proto/management.proto
> +  RuleProtocol protocol = 6;
I was hoping to be able to use arbitrary protocol numbers from https://www.iana.org/assignments/protocol-numbers/protocol-numbers.xhtml, changing that later might be more difficult

2024-06-03 16:40 UTC, bcmmbaga commented on management/proto/management.proto
> +  RuleProtocol protocol = 6;
RuleProtocol is shared between the normal firewall rules and routes firewall rules. Changing this to arbitrary protocol numbers will cause incompatibility with older clients

2024-06-04 08:33 UTC, lixmal approved these changes

2024-06-10 10:26 UTC, mlsmaycon commented on management/proto/management.proto
> +  string peerIP = 1;
let's use network ranges here instead of IPs

2024-06-10 10:59 UTC, mlsmaycon commented on management/server/route.go
> +			SourceRange: peer.IP.String(),
we need to add a /32 here

2024-07-03 08:06 UTC, merged