Adding geolocation download prompt message.
netbirdio/netbird pull request #2085
Opened 2024-06-01 07:59 UTC by keac

## Describe your changes

Adding geolocation download prompt message.
When the network condition is poor, there are no prompts when downloading the geolocation file.

## Issue ticket number and link
#2046 
### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-06-01 07:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=2085) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=2085) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=2085) it.</sub>

2024-06-03 07:50 UTC, bcmmbaga requested changes

2024-06-03 07:50 UTC, bcmmbaga commented on management/server/geolocation/database.go
Thank you for your contribution. Everything looks great overall, but I noticed that the import statement for `log "github.com/sirupsen/logrus"` is missing. This omission is causing the tests to fail. Could you please add this import statement to ensure that the code passes all tests?

2024-07-02 11:15 UTC, mlsmaycon commented
@keac, any feedback on the requested change?

2024-07-09 02:54 UTC, Anbool commented
I don't think adding an IP library download prompt will solve this problem, it's worth mentioning that it would be nice if users could customize the domain pkgs.netbird.io to avoid not being able to access areas of the pkgs.netbird.io domain.

2024-07-12 07:26 UTC, mlsmaycon approved these changes

2024-07-12 07:32 UTC, mlsmaycon commented
> I don't think adding an IP library download prompt will solve this problem, it's worth mentioning that it would be nice if users could customize the domain pkgs.netbird.io to avoid not being able to access areas of the pkgs.netbird.io domain.

thanks for the feedback, @Anbool; this PR just adds logs to the download process. Can you open a feature request for the custom domain?

2024-08-01 16:44 UTC, bcmmbaga approved these changes

2024-08-01 16:52 UTC, merged