Feature/zitadel postgres integration
netbirdio/netbird pull request #2181
Opened 2024-06-22 10:03 UTC by r0b2g1t

This PR provides an option to deploy netbird by the getting started script with the a PostgreSQL database by setting the environment variable ```ZITADEL_DATABASE``` to ```postgres```.
Which will automatically add Postgres to docker compose file and setup Zitadel with it.

The PR fix some typos aswell.

## Issue ticket number and link
- #1785 

### Checklist
- [x] Is it a bug fix
- [x] Is a feature enhancement

2024-06-22 10:09 UTC, mlsmaycon commented
Awesome PR, @r0b2g1t; thanks. We actually had in our roadmap to make Postgres the default for the installer. Can you update the following check to reflect that?

```shell
  if [[ $ZITADEL_DATABASE == "" ]]; then
    CRDB=$(renderDockerComposeCockroachDB)
    ZITADEL_DB_ENV=$(renderZidatelCockroachDBEnv)
  elif [[ $DATABASE == "postgres" ]]; then
    CRDB=$(renderDockerComposePostgres)
    ZITADEL_DB_ENV=$(renderZidatelPostgresEnv)
  fi
```

2024-06-22 10:34 UTC, r0b2g1t commented
@mlsmaycon thanks for the remark. I have set Postgres as default and added echos for the user about the usage of the environment variable.

2024-06-22 13:48 UTC, mlsmaycon requested changes
Thanks @r0b2g1t .

Can you also update the https://github.com/netbirdio/netbird/blob/main/.github/workflows/test-infrastructure-files.yml#L172 file with cockroachdb tests?

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +
```suggestion
  if [[ "$ZITADEL_DATABASE-x" == "cockroach-x" ]]; then
    echo "Use CockroachDB as Zitadel database."
    CRDB=$(renderDockerComposeCockroachDB)
    ZITADEL_DB_ENV=$(renderZidatelCockroachDBEnv)
  else  
    echo "Use Postgres as default Zitadel database."
    echo "For using CockroachDB please the environment variable 'export ZITADEL_DATABASE=cockroach'."
    CRDB=$(renderDockerComposePostgres)
    ZITADEL_DB_ENV=$(renderZidatelPostgresEnv)
  fi



```

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +
would also rename CRDB to ZDB

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +    image: 'ghcr.io/zitadel/zitadel:v2.54.3'
would update the dependency setting here:

```
    depends_on:
      zdb:
```

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +  # CockroachDB for Zitadel
service name from crdb to zdb

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +  crdb:
rename service to zdb

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +      - POSTGRES_PASSWORD=postgres
if you want to configure a random password will be better. Maybe make it persistent using a file like the temp machine key

2024-06-22 13:48 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel
Using a random password is safer.

2024-06-22 16:17 UTC, r0b2g1t commented
> Thanks @r0b2g1t .
> 
> Can you also update the https://github.com/netbirdio/netbird/blob/main/.github/workflows/test-infrastructure-files.yml#L172 file with cockroachdb tests?

I will take a look into it and will try to create tests. :-)

2024-06-22 17:15 UTC, r0b2g1t commented
> > Thanks @r0b2g1t .
> > Can you also update the https://github.com/netbirdio/netbird/blob/main/.github/workflows/test-infrastructure-files.yml#L172 file with cockroachdb tests?
> 
> I will take a look into it and will try to create tests. 🙂

@mlsmaycon I have added tests for psotgres and cockroach.

2024-06-23 09:56 UTC, r0b2g1t commented
@mlsmaycon the tests are stable. May you can take a look into it and give feedback.

2024-06-24 15:35 UTC, mlsmaycon requested changes

2024-06-24 15:35 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +  elif [[ $ZITADEL_DATABASE == "cockroach" ]]; then
this won't catch the case where the user enters ZITADEL_DATABASE=postgres

2024-06-25 09:03 UTC, mlsmaycon commented on infrastructure_files/getting-started-with-zitadel.sh
> +  elif [[ $ZITADEL_DATABASE == "cockroach" ]]; then
we will handle it after merging.

2024-06-25 09:03 UTC, mlsmaycon approved these changes

2024-06-25 09:04 UTC, mlsmaycon commented
@r0b2g1t thanks again for the amazing contribution

2024-06-25 09:10 UTC, merged