feat(client): send logs to syslog
netbirdio/netbird pull request #2259
Opened 2024-07-11 16:38 UTC by mrl5

closes #2255

## Describe your changes

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-07-11 16:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=2259) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=2259) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=2259) it.</sub>

2024-07-11 16:38 UTC, mrl5 commented
hey, go is not really "my thing" yet but I think this changes should do the trick. any suggestions from reviewers more than welcome

2024-07-12 06:36 UTC, mlsmaycon requested changes
@mrl5 thanks for your PR. I left a request to handle windows build. After fixing that you can mark the PR as ready.

2024-07-12 06:36 UTC, mlsmaycon commented on util/log.go
> +	lSyslog "github.com/sirupsen/logrus/hooks/syslog"
The syslog package is not available for Windows. We need to split the code that uses it into:

syslog_nonwindows.go <- with build tags like: `// +build !windows` and with a function that initializes the log with the syslog hook
syslog_windows.go <- with a function that does nothing

2024-07-16 08:19 UTC, mlsmaycon approved these changes
thanks for your PR @mrl5

2024-07-16 08:19 UTC, merged

2024-07-16 08:57 UTC, mrl5 commented
thanks for merging @mlsmaycon ! here is a follow-up PR that fixes some sonar qube issues https://github.com/netbirdio/netbird/pull/2276