Allow setup keys to be provided in a file
netbirdio/netbird pull request #2337
Opened 2024-07-27 15:25 UTC by moosetheory

## Describe your changes
Adds a flag and a bit of logic to allow a setup key to be passed in using a file. The flag should be exclusive with the standard `--setup-key` flag.

## Issue ticket number and link
N/A

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

#### Why?
I am attempting to set up netbird automatically in a Lix environment, but the secrets library I use requires that I write the secrets to files and ask programs to use those at runtime. I believe this change will also allow someone to use docker secrets to provide a setup key.

I am unsure what/if changes should be made to any documentation or to the README file.

(I apologize if I have missed anything, this is my first time contributing to an open source project.)

2024-07-27 15:25 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=2337) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=2337) before we can accept your contribution.<br/>**0** out of **2** committers have signed the CLA.<br/><br/>:x: Annika Merris<br/>:x: moosetheory<br/><hr/>**Annika Merris** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=2337) it.</sub>

2024-07-28 13:38 UTC, moosetheory commented
Looking at the output from the Windows testing, it seems to be in the server code, and I don't know how my tweaks could have caused it to fail, but if someone could point me in the correct direction for that error, I will take a look at trying to figure it out.

2024-08-02 13:22 UTC, mlsmaycon requested changes
Thanks for the PR @moosetheory. I've left some comments to it.

2024-08-02 13:22 UTC, mlsmaycon commented on client/cmd/login.go
> +			setupKey, err = getSetupKeyFromFile(setupKeyPath)
Better to use a new variable instead of overwriting the global used in the flags.

2024-08-02 13:22 UTC, mlsmaycon commented on client/cmd/up.go
> +	if setupKeyPath != "" && setupKey == "" {
can you move this to a single function?

2024-08-02 13:22 UTC, mlsmaycon commented on client/cmd/root.go
> +func getSetupKeyFromFile(setupKeyPath string) (string, error) {
let's use strings.TrimSpace and strings.Trim(string(data),"\n") to avoid issues

2024-08-09 15:31 UTC, mlsmaycon approved these changes
Thanks for the contribution @moosetheory. We will take the requested changes internally.

2024-08-09 15:32 UTC, merged

2024-08-09 15:54 UTC, moosetheory commented
Oh, thanks! I've been running into some test issues and have not been able to figure them out. I'm glad you are able to!

Thanks a ton!

2024-08-09 16:25 UTC, mlsmaycon commented
no worries, here is the PR in case you want to have a look https://github.com/netbirdio/netbird/pull/2411