Feature/relay integration r53
netbirdio/netbird pull request #2399
Opened 2024-08-06 15:07 UTC by pappz

## Describe your changes

Support route53 for TLS handling

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-08-06 15:24 UTC, mlsmaycon commented on relay/cmd/main.go
> +func (c Config) HasRoute54Credentials() bool {
```suggestion
func (c Config) HasRoute53Credentials() bool {
```

2024-08-20 17:42 UTC, mlsmaycon commented on relay/cmd/main.go
>  	rootCmd.PersistentFlags().StringArrayVarP(&cobraConfig.LetsencryptDomains, "letsencrypt-domains", "a", nil, "list of domains to issue Let's Encrypt certificate for. Enables TLS using Let's Encrypt.
```suggestion
	rootCmd.PersistentFlags().StringSliceVarP(&cobraConfig.LetsencryptDomains, "letsencrypt-domains", "a", nil, "list of domains to issue Let's Encrypt certificate for. Enables TLS using Let's Encrypt. Will fetch and renew certificate, and run the server with TLS")
```

This allows strings like: domain1.com,domain2.com

2024-08-20 19:44 UTC, mlsmaycon commented on encryption/route53.go
> +		certmagic.DefaultACME.CA = certmagic.LetsEncryptStagingCA
```suggestion
		certmagic.DefaultACME.CA =certmagic.LetsEncryptProductionCA
```

2024-08-20 19:46 UTC, mlsmaycon requested changes
Can you please check how we can avoid this case:

```
Your sites will be served over HTTPS automatically using an automated CA.
By continuing, you agree to the CA's terms of service.
Please enter your email address to signify agreement and to be notified
in case of issues. You can leave it blank, but we don't recommend it.
  Email address: 
```

We should not expect an interactive input when deploying the relay on containers. So we should always skip the email if the user didn't provide it

2024-08-21 07:49 UTC, pappz commented
> Can you please check how we can avoid this case:
> 
> ```
> Your sites will be served over HTTPS automatically using an automated CA.
> By continuing, you agree to the CA's terms of service.
> Please enter your email address to signify agreement and to be notified
> in case of issues. You can leave it blank, but we don't recommend it.
>   Email address: 
> ```
> 
> We should not expect an interactive input when deploying the relay on containers. So we should always skip the email if the user didn't provide it

Actually, I can not reproduce the issue on my machine (I tried with the example command that you provided), but I pushed a commit what could fix it.

2024-08-22 11:00 UTC, mlsmaycon approved these changes

2024-08-22 12:31 UTC, merged