[management] Refactor peers to use store methods
netbirdio/netbird pull request #2893
Opened 2024-11-14 16:35 UTC by bcmmbaga

## Describe your changes

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [x] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2024-11-28 10:08 UTC, pascal-fischer requested changes

2024-11-28 10:08 UTC, pascal-fischer commented on management/server/account.go
> -		defer unlock()
don't remove the lock just yet

2024-11-28 10:08 UTC, pascal-fischer commented on management/server/ephemeral.go
> +			e.addPeer(p.AccountID, p.ID, t)
the DB call already returns ephemeral peers. No need for the if and the counter, we can go Len(peers)

2024-11-28 10:08 UTC, pascal-fischer commented on management/server/http/peers_handler.go
> +		groupMinimumInfo := toGroupsInfo(peerGroups)
I wonder if it makes sense here to keep get getAllGroups approach. As the method is getAllPeers, we will probably also need close to all groups. So I would keep it as one call

2024-11-28 10:08 UTC, pascal-fischer commented on management/server/integrated_validator.go
> +	})
Not sure how much effect this transaction will have but should not hurt either

2024-11-28 10:08 UTC, pascal-fischer commented on management/server/management_proto_test.go
>  		t.Fatalf("expecting SyncResponse to have NetworkMap with 3 remote peers, got %d", len(networkMap.GetRemotePeers()))
Why do we need to update this? what changed? If so we also need to update the comment

2024-11-28 10:15 UTC, bcmmbaga commented on management/server/integrated_validator.go
> +	})
I was waiting for https://github.com/netbirdio/netbird/pull/2957 to measure the performance, but I am already planning to continue passing the account object instead of db calls, since all the methods calling this have access to the account object

2024-11-28 10:18 UTC, bcmmbaga commented on management/server/management_proto_test.go
>  		t.Fatalf("expecting SyncResponse to have NetworkMap with 3 remote peers, got %d", len(networkMap.GetRemotePeers()))
I have added the new peer in `store_with_expired_peers.sql` for the ephemeral peers tests, and this adds the counts in the network map. I will update the comment to match the number

2024-11-28 11:17 UTC, pascal-fischer commented on management/server/management_proto_test.go
>  		t.Fatalf("expecting SyncResponse to have NetworkMap with 3 remote peers, got %d", len(networkMap.GetRemotePeers()))
Ok got it, thanks

2025-01-14 13:54 UTC, pascal-fischer commented on management/server/account.go
> +			return 0, false
I am not sure we should return `0, false` here. If we have an issue connecting to the DB temporarily we would cancel the scheduler and not run any more expirations even though there might be more peers to expire. 

I would rather go with retry every 3 seconds (defined as some default retry const) and return true so the scheduler keeps running until it is absolutely sure there are no more peers to expire

2025-01-14 13:55 UTC, pascal-fischer commented on management/server/account.go
> +			return 0, false
same as above

2025-01-14 13:58 UTC, pascal-fischer commented on management/server/account.go
> +			return 0, false
same as above

2025-01-14 13:58 UTC, pascal-fischer commented on management/server/account.go
> +			return 0, false
same as above

2025-01-14 14:38 UTC, pascal-fischer commented on management/server/ephemeral.go
> -	account  *types.Account
This one is a great catch!

2025-01-14 14:46 UTC, pascal-fischer commented on management/server/http/handlers/peers/peers_handler.go
> +	groupsInfo := groups.ToGroupsInfo(groupsMap, peerID)
Inside `groups.ToGroupsInfo` we loop through the map an have no map access. We can save all the mappings from array to map for all the methods calling ToGroupsInfo if we just pass around arrays and only convert to map when actually needed

2025-01-14 15:17 UTC, pascal-fischer commented on management/server/integrated_validator.go
> +	return am.integratedPeerValidator.GetValidatedPeers(accountID, groupsMap, peersMap, settings.Extra)
The GetValidatedPeers also run only in a loop through the map. We could avoid this whole re-mapping. For all the places that still operate on account.Peers as a map we could use account.PeersG as the account object contains map and array.

Decide if we should do this as part of this PR or only leave a comment. I would like to include it just because we already touched this whole part already. If you notice this is to much change, leave it for another PR and just leave a TODO

2025-01-14 15:23 UTC, pascal-fischer commented on management/server/peer.go
> -		return false, fmt.Errorf("failed to save peer status: %w", err)
Why do we remove the error chain?

2025-01-14 15:32 UTC, pascal-fischer commented on management/server/peer.go
> +		return status.NewPeerNotPartOfAccountError()
We should also check the user.Account
```
	user, err := am.Store.GetUserByUserID(ctx, store.LockingStrengthShare, userID)
	if err != nil {
		return nil, err
	}

	if user.AccountID != accountID {
		return nil, status.NewUserNotPartOfAccountError()
	}
```

2025-01-14 16:00 UTC, pascal-fischer commented on management/server/peer.go
> +	}
lets do this check on the very top before loading the account

2025-01-14 16:02 UTC, pascal-fischer commented on management/server/peer.go
> +		return 0, false
same as above

2025-01-14 16:03 UTC, pascal-fischer commented on management/server/peer.go
> +		return 0, false
same as above

2025-01-14 16:04 UTC, pascal-fischer commented on management/server/peer.go
> +		return 0, false
same as above

2025-01-14 16:04 UTC, pascal-fischer commented on management/server/peer.go
> +		return 0, false
same as above

2025-01-14 17:07 UTC, bcmmbaga commented on management/server/http/handlers/peers/peers_handler.go
> +	groupsInfo := groups.ToGroupsInfo(groupsMap, peerID)
`groups.ToGroupsInfo ` is currently used by network resources, which also pass a map from the groups manager. Changing this now would require significant modifications to the network resources.

2025-01-20 17:41 UTC, pascal-fischer approved these changes

2025-01-20 17:41 UTC, merged