fix(acl): update each peer's network when rule,group or peer changed
netbirdio/netbird pull request #333
Opened 2022-05-26 14:48 UTC by gigovich

2022-05-30 20:14 UTC, mlsmaycon requested changes

2022-05-30 20:14 UTC, mlsmaycon commented on management/server/group.go
> +	fmt.Println("+++", group.Peers)
left-over print?

2022-05-30 20:14 UTC, mlsmaycon commented on management/server/group.go
> +			}
We are missing handling PeerKeyId2SrcRulesId and PeerKeyId2DstRulesId cleanup at this point

2022-05-30 20:14 UTC, mlsmaycon commented on management/server/group.go
> -	return am.Store.SaveAccount(account)
We are missing handling PeerKeyId2SrcRulesId and PeerKeyId2DstRulesId cleanup here

2022-05-30 20:14 UTC, mlsmaycon commented on management/server/rule.go
> +	account.Network.IncSerial()
We are missing handling PeerKeyId2SrcRulesId and PeerKeyId2DstRulesId cleanup here too

2022-06-01 15:21 UTC, gigovich commented on management/server/group.go
> +			}
@mlsmaycon I'm not sure I understand it, because we rebuild these indexes in the `Store.SaveAccount` method.

2022-06-01 17:21 UTC, mlsmaycon commented on management/server/group.go
> +			}
@gigovich on the store we seem to only handle adding rules to PeerKeyId2SrcRulesId and PeerKeyId2DstRulesId maps, but we don't remove a rule from a peer that peer was removed from a group, or when a group is removed from a rule. The same goes for when a peer is removed from the account, there is no delete(PeerKeyId2SrcRulesId, key)

2022-06-02 16:16 UTC, gigovich commented on management/server/group.go
> +			}
Fixed. Reset them before updating in `Store.SaveAccount` https://github.com/netbirdio/netbird/pull/333/files#diff-14bee3eff6b719cef1943d98a2d97bcb4ad24cc1f5429cabde0ec4d30381aa81R243

2022-06-02 16:48 UTC, mlsmaycon commented on management/server/group.go
> +			}
@gigovich this reset is removing the maps of peers from all accounts.

2022-06-02 18:59 UTC, gigovich commented on management/server/group.go
> +			}
https://github.com/netbirdio/netbird/pull/333/commits/fb2cf2c4c945a1a1bf08387c93cdbc2f3bef6ace
@mlsmaycon 

1. Clean indexes when removing peers.
2. Clean only account peers from indexes during the save call.

2022-06-04 20:02 UTC, merged