NetBird SSH
netbirdio/netbird pull request #361
Opened 2022-06-12 12:13 UTC by braginini

2022-06-14 10:26 UTC, braginini commented
If an agent has been upgraded from any version without SSH support, all others won't receive an update indicating that SSH is now possible to this peer.
Should be fixed

2022-06-18 13:18 UTC, mlsmaycon requested changes

2022-06-18 13:18 UTC, mlsmaycon commented on client/internal/config.go
> +		if preSharedKey == "**********" || preSharedKey == "" {
we shouldn't dismiss empty string as sometimes user wants to remove a preshared key from its config

2022-06-18 13:18 UTC, mlsmaycon commented on client/internal/engine.go
> +				fmt.Sprintf("%s:%d", e.wgInterface.Address.IP.String(), 2222))
port should come from config for cases when port 2222 is already in use

2022-06-18 13:18 UTC, mlsmaycon commented on client/internal/engine.go
> +			go func() {
In the event of an error (e.g. port in use), we should clean the e.sshServer

2022-06-18 13:18 UTC, mlsmaycon commented on client/internal/engine_test.go
> +	engine := NewEngine(ctx, cancel, &signal.MockClient{}, &mgmt.MockClient{}, &EngineConfig{
lets avoid using same interface configuration between tests

2022-06-18 13:18 UTC, mlsmaycon commented on client/internal/engine.go
> +	SSHKey []byte
We should distinguish private and public ssh keys, here we store private key but other methods use sshKey for public SSH Key (e.g. Login)

2022-06-18 13:18 UTC, mlsmaycon commented on client/ssh/server.go
> +func (srv *DefaultServer) sessionHandler(s ssh.Session) {
let's avoid using single-letter input variables

2022-06-18 13:18 UTC, mlsmaycon commented on client/ssh/server.go
> +func (srv *DefaultServer) stdInOut(f *os.File, s ssh.Session) {
let's avoid using single-letter input variables

2022-06-18 13:18 UTC, mlsmaycon commented on client/ssh/util.go
> +func GeneratePrivateKey(t KeyType) ([]byte, error) {
let's avoid using single-letter input variables

2022-06-18 13:18 UTC, mlsmaycon commented on client/ssh/window_unix.go
> +func setWinSize(f *os.File, w, h int) {
let's avoid using single-letter input variables

2022-06-18 13:18 UTC, mlsmaycon commented on client/ssh/window_windows.go
> +func setWinSize(f *os.File, w, h int) {
let's avoid using single-letter input variables

2022-06-18 13:18 UTC, mlsmaycon commented on management/server/grpcserver.go
> +
can't put his comment in line 273, but should we use the peer key from the PeerKeys payload?

2022-06-18 13:18 UTC, mlsmaycon commented on management/server/grpcserver.go
> +		SshConfig: &proto.SSHConfig{SshEnabled: true},                 //TODO REMOVE THIS HARDCODED VALUE
remove hardcoded flag

2022-06-23 14:58 UTC, mlsmaycon approved these changes

2022-06-23 15:04 UTC, merged