fix High Availability routing
netbirdio/netbird pull request #612
Opened 2022-12-06 12:42 UTC by nazarewk

## Describe your changes

It prevents Server from adding rules to route direct-acces/own networks through VPN when the route is in HA mode (has more than 1 entry)

## Issue ticket number and link

fixes: https://github.com/netbirdio/netbird/issues/598

### Checklist
- [x] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [x] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2022-12-06 12:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=612) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=612) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=612) it.</sub>

2022-12-06 23:21 UTC, mlsmaycon requested changes
Thank you so much for your PR @nazarewk, it is definitely helping with the case you described. 

I have a few notes that I took into consideration on my request for changes: 

In multi-hop routing cases, you want to route traffic via the VPN interface as the routing peer might be an intermediate router. In that case, will make sense to have different network routes for each hop.

Also, to document, with PR #606 we will be able to prevent similar case by using different distribution groups for routes, but only when different groups are used with routes and peers.

2022-12-06 23:21 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
An HA route is composed of multiple routes that have the same combination of `newRoute.NetID` and the `newRoute. Network`. With that in mind,  The best way to index the map will be with:

`newRoute.NetID + "-" +  newRoute.Network.String()`

You can also use the function `getClientNetworkID`, which generates this HA combination. It makes sense to rename it to `getHANetworkID`


Another point. It will be better to move the OS check and the route registration to this loop, as when creating firewall rules, we use the route ID to comment, and track route and firewall operations. Plus we shouldn't register other peer's routes from the HA group as ours as well.

2022-12-06 23:21 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +			if _, ok := ownNetIDs[newRoute.NetID]; ok {
Moving the server route registration code to the previous loop allows having only code for non-owned network IDs.

Also, as the ownNetIDs values are booleans, you can skip the retrieved check and only check for the map lookup value. e.g.:

```Go
if !ownNetIDs[newRoute.NetID] {
   // client code
   ...
}```

2022-12-06 23:21 UTC, mlsmaycon commented on client/internal/routemanager/manager_test.go
> +			name: "HA server should not route it's own networks through VPN",
I suggest the following name for this test:

`HA server should not register routes from the same HA group`

2022-12-07 09:40 UTC, nazarewk commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
Done the first part, but I am not sure about second part as I'm not familiar with the codebase.

To me it looks like moving the OS check to the first loop would result in those routes being created as `newClientRoutesIDMap` therefore it is not desired?

2022-12-07 09:42 UTC, nazarewk commented on client/internal/routemanager/manager.go
> +			if _, ok := ownNetIDs[newRoute.NetID]; ok {
wouldn't it throw some kind of error when key is missing?

2022-12-07 09:54 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
It won't, as the other routes that we will drop should be routed by the other peers in an HA group. Which didn't happen in the previous version of the code, and they ended up registered as client routes which caused the loop behavior you are solving now.

2022-12-08 07:42 UTC, nazarewk commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
Is this what you meant? [`741bfe4` (#612)](https://github.com/netbirdio/netbird/pull/612/commits/741bfe46945eacbc499a22c40038bf519460faea)

2022-12-08 07:52 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
Almost, just in the second loop we don't need to register the server routes anymore, so we can just validate if it is not a route the server owns and register as new client route: 

From:
```Go
if ownNetworkIDs[networkID] {
				newServerRoutesMap[newRoute.ID] = newRoute
			} else {
```	
To:
```Go
if !ownNetworkIDs[networkID] {
       newClientRoutesIDMap[networkID] = append(newClientRoutesIDMap[networkID], newRoute)
```

2022-12-08 08:37 UTC, nazarewk commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
So we're effectively deleting `newServerRoutesMap` handling alltogether?

2022-12-08 08:55 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
No, we are moving it to the first loop as there we will check for owned routes and we can register them already. So checking again in the second loop is not needed

2022-12-08 10:08 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
Here is an example of what I meant in the previous comments:
```Go
		for _, newRoute := range newRoutes {
			if newRoute.Peer == m.pubKey {
				// only linux is supported for now
				if runtime.GOOS != "linux" {
					log.Warnf("received a route to manage, but agent doesn't support router mode on %s OS", runtime.GOOS)
					continue
				}
				ownNetworkIDs[getHANetworkID(newRoute)] = true
                                newServerRoutesMap[newRoute.ID] = newRoute
			}
		}
```

2022-12-08 10:17 UTC, nazarewk commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
After introducing this change the test now creates 2 Server routes instead of 3, is it intended?

2022-12-08 10:23 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				ownNetIDs[newRoute.NetID] = true
Yes, it is; the change is skipping the route with ID `r1` as the routing peer is a remote peer.

2022-12-08 10:57 UTC, mlsmaycon commented on client/internal/routemanager/manager.go
> +				// only linux is supported for now
We should register the owned network before checking the OS. This is the cause of the failing tests

2022-12-08 12:19 UTC, mlsmaycon approved these changes
@nazarewk thank you for the changes and hanging thought all the requests.

2022-12-08 12:19 UTC, merged