Add external-ip-map flag for ICE nat 1:1 candidates
netbirdio/netbird pull request #652
Opened 2023-01-12 11:20 UTC by mlsmaycon

## Describe your changes

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [ ] Is a feature enhancement
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-01-15 11:53 UTC, mlsmaycon commented
Still a pain to add new flags mainly caused by the current behavior and daemon communication. 

It might make sense for us to refactor this whole thing or change the behavior for updating daemon settings

2023-01-17 10:42 UTC, braginini requested changes

2023-01-17 10:42 UTC, braginini commented on client/cmd/root.go
> +	upCmd.PersistentFlags().StringVar(&customDNSAddress, dnsResolverAddress, "", "Sets a custom address for NetBird's local DNS resolver. If set, the agent won't attempt to discover the best ip and port
Would be great to mention that if an empty string is provided, it will clean the IPs, e.g.:
```
--external-ip-map ""
```

2023-01-17 18:00 UTC, braginini approved these changes

2023-01-17 18:16 UTC, merged