Add Keycloak Idp Manager
netbirdio/netbird pull request #746
Opened 2023-03-16 16:10 UTC by bcmmbaga

## Describe your changes
Added intergration with keycloak user API.

## Issue ticket number and link

* Keycloak integration - Peer detail does not show Username  ([#601][i601])
* Usernames are not saved  ([#716][i716])
* Usernames are not displayed for peers ([#724][i724])

[i601]: https://github.com/netbirdio/netbird/issues/601
[i716]: https://github.com/netbirdio/netbird/issues/716
[i724]: https://github.com/netbirdio/netbird/issues/724

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-03-16 16:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/netbirdio/netbird?pullRequest=746) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/netbirdio/netbird?pullRequest=746) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/netbirdio/netbird?pullRequest=746) it.</sub>

2023-03-16 16:53 UTC, braginini commented
Thank you, @bcmmbaga, for this contribution! I triggered checks. We will have a look into the code soon.

2023-03-20 10:25 UTC, pappz commented
Thank you for the pull request!
Could you share with me some details about how what is the proper way to setup the client on Keycloak admin interface?
I tried based on [this](https://netbird.io/docs/integrations/identity-providers/self-hosted/using-netbird-with-keycloak) documentation.

2023-03-20 19:37 UTC, bcmmbaga commented
@pappz To configure keycloak you need to create two separate clients - one for the frontend using `authorization_code` grant type and another for the backend using `client_credentials` grant. It is necessary to do so because if both of these grants are enabled in a single client, it will result in the frontend login not functioning properly.

1. For the frontend client with `authorization_code` grant use [this](https://netbird.io/docs/integrations/identity-providers/self-hosted/using-netbird-with-keycloak).
2. For Backend client with `client_credentials` grant

      - Create new client with `Client Type: OpenID Connect` and `Client ID: netbird-backend`
         ![image](https://res.cloudinary.com/dlu51vt8c/image/upload/v1679339289/keycloak/Screenshot_2023-03-20_at_22.04.29_kzddhn.png)

      - Check the checkboxes as on the screenshot below and click Save
      ![capability config](https://res.cloudinary.com/dlu51vt8c/image/upload/v1679339589/keycloak/Screenshot_2023-03-20_at_22.12.42_cbxgst.png)
      
      - Go to clients and select `netbird-backend`
      ![netbird-backend client](https://res.cloudinary.com/dlu51vt8c/image/upload/v1679339781/keycloak/Screenshot_2023-03-20_at_22.15.56_alxjau.png)
      
      - Click `Credentials` tab and you can copy` client secret` from there
      ![credentials](https://res.cloudinary.com/dlu51vt8c/image/upload/v1679339970/keycloak/Screenshot_2023-03-20_at_22.19.08_qpepxi.png)
      
      - Click `Service accounts roles` tab and click Assign roles
        
         Select `Filter by clients` and search for manage-users 
         ![assign roles](https://res.cloudinary.com/dlu51vt8c/image/upload/v1679340389/keycloak/Screenshot_2023-03-20_at_22.26.10_z5yqtt.png)
         
         Check the role checkbox and click assign
         ![role assigned](https://res.cloudinary.com/dlu51vt8c/image/upload/v1679340665/keycloak/Screenshot_2023-03-20_at_22.30.47_fpmwpe.png)

2023-03-22 07:44 UTC, pappz commented
Thank you for the description! Now I can login to the dashboard without any error message but the client registration still failed. What do you think, what can goes wrong?

Managemenet service:
```
sudo ./management management --config ~/netbird/conf_mgm_keycloack.json --datadir datadir/ --log-level trace --log-file console --dns-domain netbird.cloud
INFO[0000] loading OIDC configuration from the provided IDP configuration endpoint http://localhost:8080/realms/netbird/.well-known/openid-configuration 
INFO[0000] loaded OIDC configuration from the provided IDP configuration endpoint: http://localhost:8080/realms/netbird/.well-known/openid-configuration 
INFO[0000] overriding HttpConfig.AuthIssuer with a new value http://localhost:8080/realms/netbird, previously configured value: http://localhost:8080/realms/netbird 
INFO[0000] overriding HttpConfig.AuthKeysLocation (JWT certs) with a new value http://localhost:8080/realms/netbird/protocol/openid-connect/certs, previously configured value: http://localhost:8080/realms/netbird/protocol/openid-connect/certs 
INFO[0000] overriding DeviceAuthorizationFlow.TokenEndpoint with a new value: http://localhost:8080/realms/netbird/protocol/openid-connect/token, previously configured value: http://localhost:8080/realms/netbird/protocol/openid-connect/token 
INFO[0000] overriding DeviceAuthorizationFlow.DeviceAuthEndpoint with a new value: http://localhost:8080/realms/netbird/protocol/openid-connect/auth/device, previously configured value: http://localhost:8080/realms/netbird/protocol/openid-connect/token 
INFO[0000] overriding DeviceAuthorizationFlow.ProviderConfig.Domain with a new value: localhost:8080, previously configured value: localhost:8080 
2023-03-21T23:23:04+01:00 INFO management/server/telemetry/app_metrics.go:144: enabled application metrics and exposing on http://0.0.0.0:8081
2023-03-21T23:23:04+01:00 INFO management/server/account.go:655: single account mode enabled, accounts number 1
2023-03-21T23:23:04+01:00 DEBG management/server/idp/keycloak.go:144: requesting new jwt token for keycloak idp manager
2023-03-21T23:23:04+01:00 INFO management/cmd/management.go:221: running gRPC backward compatibility server: [::]:33073
2023-03-21T23:23:04+01:00 INFO management/cmd/management.go:253: running HTTP server and gRPC server on the same port: [::]:80
2023-03-21T23:23:04+01:00 INFO management/server/account.go:841: warmed up IDP cache with 0 entries
2023-03-21T23:23:15+01:00 DEBG management/server/grpcserver.go:266: Login request from peer [ehRU6p4h5wD7uEGzyimMm2BbxlBPa6iIBrwXkB3kXTo=] [[::1]:45400]
2023-03-21T23:23:15+01:00 WARN management/server/grpcserver.go:306: failed logging in peer ehRU6p4h5wD7uEGzyimMm2BbxlBPa6iIBrwXkB3kXTo=
```
Client:
```
2023-03-22T08:42:17+01:00 DEBG client/internal/login.go:71: peer registration required
2023-03-22T08:42:17+01:00 ERRO client/internal/login.go:58: failed logging-in peer on Management Service : rpc error: code = InvalidArgument desc = invalid setup-key or no sso information provided, err: invalid UUID length: 0
2023-03-22T08:42:17+01:00 DEBG client/internal/device_auth.go:53: connecting to Management Service http://localhost:80
2023-03-22T08:42:17+01:00 DEBG client/internal/device_auth.go:59: connected to the Management service http://localhost:80
Error: foreground login failed: interactive sso login failed: getting a request device code failed: request device code returned status 401 error: {"error":"unauthorized_client","error_description":"Invalid client or Invalid client credentials"}
```
Keycloak:
```
2023-03-22 07:42:48,909 WARN  [org.keycloak.events] (executor-thread-94) type=OAUTH2_DEVICE_AUTH_ERROR, realmId=9d788982-271f-4f7e-9413-9e88bd502ccd, clientId=netbird-backend, userId=null, ipAddress=172.17.42.1, error=invalid_client_credentials
```

2023-03-22 07:51 UTC, bcmmbaga commented
> 

can you share your `conf_mgm_keycloack.json`?

2023-03-22 11:26 UTC, mlsmaycon commented on management/server/idp/keycloak.go
> +	accountID := kp.Attributes.Get("wp_account_id")
@bcmmbaga There is a small typo here, it should be `wt_account_id`. Perhaps is worth introducing a constant for the attributes, to avoid typos.

2023-03-22 15:01 UTC, pappz requested changes

2023-03-22 15:01 UTC, pappz commented on management/server/idp/keycloak.go
> +	if !strings.HasPrefix(strings.ToLower(config.AdminEndpoint), "https://") {
Could you remove the SSL enforcement, please. In debug environment the life is easier without SSL.

2023-03-22 15:01 UTC, pappz commented on management/server/idp/keycloak.go
> +	if !strings.HasPrefix(strings.ToLower(config.TokenEndpoint), "https://") {
Same as line 98.

2023-03-22 15:42 UTC, bcmmbaga commented
> > > 
> > 
> > 
> > can you share your `conf_mgm_keycloack.json`?
> 
> @bcmmbaga meanwhile @mlsmaycon helped to debug what was my issue. The client id was incorrect in the device auth flow.

Great 👍🏽

2023-03-22 21:55 UTC, mlsmaycon commented
@bcmmbaga we got some tests failing

2023-03-22 22:05 UTC, bcmmbaga commented
> @bcmmbaga we got some tests failing

It's resolved now. I overlooked pushing the unit test fix after removing the SSL enforcement for the URL.

2023-03-22 22:10 UTC, mlsmaycon commented
Thanks, we have some update to work on regarding the user invites. Now we are leaving for the IDP to update the `wt_pending_invite` attribute, but it seems like we can't do that with Keycloak. but that is for another PR.

We will need to add this in the docs as a known issue. The same goes for updating existing users attributes with the account ID before enabling Keycloak management, to avoid cache request on every API call.

2023-03-22 22:26 UTC, bcmmbaga commented
> Thanks, we have some update to work on regarding the user invites. Now we are leaving for the IDP to update the `wt_pending_invite` attribute, but it seems like we can't do that with Keycloak. but that is for another PR.
> 
> We will need to add this in the docs as a known issue. The same goes for updating existing users attributes with the account ID before enabling Keycloak management, to avoid cache request on every API call.

Correct. Regarding updating existing users,  at the moment when user login attributes are updated, does caching affect this or we have to update all users simultaneously in a batch?

2023-03-22 22:36 UTC, mlsmaycon commented
> > Thanks, we have some update to work on regarding the user invites. Now we are leaving for the IDP to update the `wt_pending_invite` attribute, but it seems like we can't do that with Keycloak. but that is for another PR.
> > We will need to add this in the docs as a known issue. The same goes for updating existing users attributes with the account ID before enabling Keycloak management, to avoid cache request on every API call.
> 
> Correct. Regarding updating existing users, at the moment when user login attributes are updated, does caching affect this or we have to update all users simultaneously in a batch?

The cache will be dismissed as invalid until all users in local storage matches a UserData from the cache. It will eventually update when every user logs in, but to avoid issues is better to drive the folks in updating the attributes for all users in keycloak

2023-03-23 13:54 UTC, merged

2023-03-27 19:20 UTC, helmut72 commented
> * Click `Credentials` tab and you can copy` client secret` from there

Where must this be pasted?

2023-03-29 10:44 UTC, giezi commented
@helmut72 

Please configure it like this (Keycloak 21.01):

`    "IdpManagerConfig": {
        "Manager": "none",
	"ManagerType": "keycloak",
        "KeycloakClientCredentials": {
          "ClientID": "netbird-backend",
          "ClientSecret": "<client-secret-from-keycloak>",
          "GrantType": "client_credentials",
          "TokenEndpoint": "https://<keycloak-url>/realms/netbird/protocol/openid-connect/token",
          "AdminEndpoint": "https://<keycloak-url>/admin/realms/netbird"
	}
     },
`

In Keycloak configured this:
https://github.com/netbirdio/netbird/pull/746#issuecomment-1476827246

2023-03-29 18:02 UTC, bcmmbaga commented
> Thanks for the hint, but now this error appear:
> 
> ```
> Error: failed retrieving a new idp manager with err: invalid manager type: keycloak
> ```
> 
> Using latest Docker image from 5 days ago.

Get the most recent docker image that was released 3 days ago.

2023-03-29 18:04 UTC, helmut72 commented
Tried now `netbirdio/xxx:0.14.5`, error goes away. Now I got error 500, invalid JWT in the browser. Without IdpManagerConfig, login works without problems.

2023-03-29 18:12 UTC, bcmmbaga commented
> Tried now `netbirdio/xxx:0.14.5`, error goes away. Now I got error 500, invalid JWT in the browser. Without IdpManagerConfig, login works without problems.

Could you please share  netbird logs?

2023-03-29 18:20 UTC, helmut72 commented
last few logs after starting the container:

```
2023-03-29T18:13:42Z INFO management/server/telemetry/app_metrics.go:144: enabled application metrics and exposing on http://0.0.0.0:8081
2023-03-29T18:13:42Z INFO management/server/account.go:632: single account mode disabled, accounts number 0
2023-03-29T18:13:42Z INFO management/cmd/management.go:221: running gRPC backward compatibility server: [::]:33073
2023-03-29T18:13:42Z INFO management/cmd/management.go:253: running HTTP server and gRPC server on the same port: [::]:80
2023-03-29T18:13:42Z INFO management/server/account.go:817: warmed up IDP cache with 0 entries
```

Then I login to the dashboard and only these logs appear:

```
2023-03-29T18:14:41Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 637889294: GET /api/users status 500
2023-03-29T18:14:41Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 915129259: GET /api/users status 500
2023-03-29T18:14:41Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 3290001764: GET /api/groups status 500
2023-03-29T18:14:41Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 2179991111: GET /api/routes status 500
2023-03-29T18:14:41Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 761902825: GET /api/peers status 500
```

Is there any --verbose or --debug switch?

2023-03-29 18:29 UTC, helmut72 commented
I don't became "admin":

<img width="617" alt="Bildschirmfoto 2023-03-29 um 20 26 03" src="https://user-images.githubusercontent.com/1388751/228633438-c6082091-666b-4ad4-816e-b841e66307c7.png">

Here are more logs with --log-level debug (replaced my domain with example.com):

```
2023-03-29T18:23:47Z DEBG management/server/file_store.go:219: acquiring global lock
2023-03-29T18:23:47Z DEBG management/server/account.go:1325: creating new account
2023-03-29T18:23:47Z DEBG management/server/account.go:1342: created new account cgi84cp9faic73b75hug with setup key EA1C0212-3D28-45EB-8260-22F6BE33D309
2023-03-29T18:23:47Z DEBG management/server/file_store.go:225: released global lock in 520.286µs
2023-03-29T18:23:47Z DEBG management/server/account.go:901: looking up user user1@bauer-bag.de of account cgi84cp9faic73b75hug in cache
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z DEBG management/server/idp/keycloak.go:430: updating IdP metadata for user user1@bauer-bag.de
2023-03-29T18:23:47Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 2998283582: GET /api/users status 500
2023-03-29T18:23:47Z DEBG management/server/file_store.go:219: acquiring global lock
2023-03-29T18:23:47Z DEBG management/server/file_store.go:225: released global lock in 32.438µs
2023-03-29T18:23:47Z DEBG management/server/account.go:901: looking up user user1@bauer-bag.de of account cgi84cp9faic73b75hug in cache
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z DEBG management/server/file_store.go:219: acquiring global lock
2023-03-29T18:23:47Z DEBG management/server/file_store.go:219: acquiring global lock
2023-03-29T18:23:47Z DEBG management/server/file_store.go:225: released global lock in 462.461µs
2023-03-29T18:23:47Z DEBG management/server/account.go:901: looking up user user1@bauer-bag.de of account cgi84cp9faic73b75hug in cache
2023-03-29T18:23:47Z DEBG management/server/file_store.go:225: released global lock in 194.029µs
2023-03-29T18:23:47Z DEBG management/server/account.go:947: one request to get account cgi84cp9faic73b75hug is already running
2023-03-29T18:23:47Z DEBG management/server/account.go:901: looking up user user1@bauer-bag.de of account cgi84cp9faic73b75hug in cache
2023-03-29T18:23:47Z DEBG management/server/account.go:947: one request to get account cgi84cp9faic73b75hug is already running
2023-03-29T18:23:47Z DEBG management/server/file_store.go:219: acquiring global lock
2023-03-29T18:23:47Z DEBG management/server/file_store.go:225: released global lock in 13.928µs
2023-03-29T18:23:47Z DEBG management/server/account.go:901: looking up user user1@bauer-bag.de of account cgi84cp9faic73b75hug in cache
2023-03-29T18:23:47Z DEBG management/server/account.go:947: one request to get account cgi84cp9faic73b75hug is already running
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z DEBG management/server/idp/keycloak.go:430: updating IdP metadata for user user1@bauer-bag.de
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 2870900255: GET /api/users status 500
2023-03-29T18:23:47Z DEBG management/server/idp/keycloak.go:430: updating IdP metadata for user user1@bauer-bag.de
2023-03-29T18:23:47Z DEBG management/server/account.go:876: account cgi84cp9faic73b75hug not found in cache, reloading
2023-03-29T18:23:47Z DEBG management/server/account.go:947: one request to get account cgi84cp9faic73b75hug is already running
2023-03-29T18:23:47Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 4114408966: GET /api/groups status 500
2023-03-29T18:23:47Z DEBG management/server/idp/keycloak.go:430: updating IdP metadata for user user1@bauer-bag.de
2023-03-29T18:23:47Z DEBG management/server/idp/keycloak.go:430: updating IdP metadata for user user1@bauer-bag.de
2023-03-29T18:23:47Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 1234329662: GET /api/peers status 500
2023-03-29T18:23:47Z ERRO management/server/telemetry/http_api_metrics.go:150: HTTP response 1133415539: GET /api/routes status 500
```

2023-03-29 18:46 UTC, helmut72 commented
This is the jwt token:

```
{
  "header": {
    "alg": "RS256",
    "typ": "JWT",
    "kid": "xWU9JP5y-HqVVOea0sSEbMXLxbBoQSIltvKIGN8-xxx"
  },
  "payload": {
    "exp": 1680115546,
    "iat": 1680115246,
    "auth_time": 1680115246,
    "jti": "8d7a17fa-2c08-4420-ae1b-dbe6b5f7cxxx",
    "iss": "https://keycloak.example.com/realms/netbird",
    "aud": [
      "netbird-client",
      "account"
    ],
    "sub": "user1@example.com",
    "typ": "Bearer",
    "azp": "netbird-client",
    "session_state": "7c126780-xxxx-xxxx-xxxx-c6b805ddbxxx",
    "acr": "1",
    "allowed-origins": [
      "https://netbird.example.com"
    ],
    "realm_access": {
      "roles": [
        "default-roles-auth",
        "offline_access",
        "uma_authorization"
      ]
    },
    "resource_access": {
      "account": {
        "roles": [
          "manage-account",
          "manage-account-links",
          "view-profile"
        ]
      }
    },
    "scope": "openid api offline_access email profile",
    "sid": "7c126780-xxxx-xxxx-xxxx-c6b805ddbxxx",
    "email_verified": true,
    "name": "user 1",
    "preferred_username": "user1",
    "given_name": "user",
    "family_name": "1",
    "email": "user1@example.com"
  },
  "signature": "...."
}
```

2023-05-15 12:23 UTC, MohammedNoureldin commented
Hi,

will this somehow allow the fetched to used to be automatically assigned to a group (e.g. admin) according to its Keycloak groups? This feature would be great.