Add service user logic and endpoints to management server
netbirdio/netbird pull request #791
Opened 2023-04-06 15:03 UTC by pascal-fischer

## Describe your changes
- extend user object with flag for service users
- update user get endpoint to set query filter for service users (or not)
- split service user creation / inviting from idp
- allow user deletion (only for service users)

Whats missing:
- permission validation of operations in AccountManager (will be discussed separatly, for now accesscontrol middleware will block the requests)
- activity events (require update for all user related events to set isServiceUser flag to distinguish)

## Issue ticket number and link
https://github.com/netbirdio/netbird/issues/718

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-04-13 09:03 UTC, pappz requested changes

2023-04-13 09:03 UTC, pappz commented on management/server/user.go
>  // NewRegularUser creates a new user with role UserRoleAdmin
Invalid comment

2023-04-13 09:27 UTC, pappz requested changes

2023-04-13 09:27 UTC, pappz commented on management/server/user.go
> +	// _, err = am.refreshCache(account.Id)
Please remove unused codes

2023-04-13 09:27 UTC, pappz commented on management/server/user.go
- The UserStatusDisabled is unused. Please remove
- In the inviteNewUser the user's status will be UserStatusInvited or not?

2023-04-13 10:58 UTC, pascal-fischer commented on management/server/user.go
Regarding the UserStatusDisabled. I would keep it because it comes from the API protocol and there we use all 3 constants. Just in code we don't need it right now but I would rather keep it. 

Regarding the UserStatusInvited, you are right, it is set in user.go L84

2023-04-13 10:58 UTC, pascal-fischer commented on management/server/user.go
> +	// _, err = am.refreshCache(account.Id)
done

2023-04-13 10:58 UTC, pascal-fischer commented on management/server/user.go
>  // NewRegularUser creates a new user with role UserRoleAdmin
done

2023-04-17 13:45 UTC, pappz approved these changes

2023-04-17 14:39 UTC, merged