Add Google Workspace IdP
netbirdio/netbird pull request #949
Opened 2023-06-11 20:54 UTC by bcmmbaga

## Describe your changes

## Issue ticket number and link

### Checklist
- [ ] Is it a bug fix
- [ ] Is a typo/documentation fix
- [x] Is a feature enhancement
- [ ] It is a refactor
- [ ] Created tests that fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

2023-06-15 10:39 UTC, pascal-fischer submitted a review, later dismissed

2023-06-15 16:42 UTC, mlsmaycon requested changes
please check my comment on base64 env variable

2023-06-15 16:42 UTC, mlsmaycon commented on management/server/idp/idp.go
> +			ServiceAccountKeyPath: config.ExtraConfig["ServiceAccountKeyPath"],
We should use a base64 value, to avoid making the user map a local file

2023-06-19 14:03 UTC, pascal-fischer approved these changes

2023-06-20 17:14 UTC, mlsmaycon approved these changes

2023-06-20 17:15 UTC, merged